### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-overlays#1]
`react-overlays` is available on npm, but not sure its a good name; just the first one that came to mind. There is non-overlay related stuff here, like `RootClose` and `Transition` as well

**Comment by AlexKVal** [comment]
maybe split more ?
into two-three projects ?

**Comment by taion** [comment]
I like `react-overlays` as a name. `RootClose` is (hopefully?) pretty specific to overlays and overlay-like things. Not sure about `Transition`, but it doesn't need to be perfect.

**Comment by pieterv** [comment]
Hey @jquense, not sure if you have seen https://github.com/pieterv/react-layers but i created it a while ago as an abstraction of the work i did on the initial react-bootstrap overlays, it haven't had the time to keep it up to date but i still think the API's are relevant. Anyway its great to see someone taking these ideas further. Also let me know if you want the `react-layers` NPM package name for this work.

**Comment by jquense** [comment]
hey @pieterv thanks for the offer :) I am not sure if its worth it to take over the name (everyone else's thoughts?). I did see react-layers a while ago and actually just thought of it again as I was putting together the [`ModalManager`](https://github.com/react-bootstrap/react-overlays/blob/master/src/ModalManager.js) which is more specific of a use case, but it made me think about a more generic container/layer set of classes. Package name aside I am going to take a look through the react-layer code since I think a good low level layer abstraction is still missing here.

**Comment by pieterv** [comment]
No worries, I thought that would be the case. Sure! let me know if you have any questions.
