### ISSUE TITLE
Support useRootClose inside open shadow roots

### ISSUE THREAD

**Issue by charlesroelli** [react-bootstrap/react-overlays#1005]
## Describe the bug

useRootClose doesn't work inside a shadow root as it inspects `Event.target` instead of `Event.composedPath()[0]`, miscalculating the clicked element as the event is re-targeted to the shadow host.

## To Reproduce

Revert the change to `src/useRootClose.ts` in #1004, and run the new tests.

## Reproducible Example

See the fix + test added in #1004.

## Expected behavior

useRootClose should work correctly in shadow roots.

**Comment by kyletsang** [comment]
Fixed in #1004
