### ISSUE TITLE
Unknown props when using Overlay

### ISSUE THREAD

**Issue by henrikbjorn** [react-bootstrap/react-overlays#103]
Using React 15.2.0 and react-overlays 0.6.4 results in the following Warning in the console while using the `Overlay` component.

```
warning.js?8a56:44 Warning: Unknown props `placement`, `arrowOffsetLeft`, `arrowOffsetTop`, `positionLeft`, `positionTop` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Select)
    in Position (created by Overlay)
    in div (created by RootCloseWrapper)
    in RootCloseWrapper (created by Overlay)
```

Some code that shows how i use the `Overlay` component so that it is clear that my code isn't sending down wierd props.

``` jsx
        <Overlay placement="bottom" show={open} rootClose container={this} onHide={this.handleHide} target={this.handleTarget}>
          <div className={styles.menu}>
            {children.map((child, index) => {
              return React.cloneElement(child, {
                active: selected == index,
                onClick: this.handleSelect,
              })
            })}
          </div>
        </Overlay>
```

**Comment by taion** [comment]
Overlay injects positioning props into its child. That's how Overlay does its thing. As such you'll need to render a custom component there and only pass down known props to the div. There's not really any way around this, since in the general case Overlay needs to communicate placement information to its child.

**Comment by jquense** [comment]
this is a bit of an unfortunate consequence of the new change to React it makes the niceity of being able to use a plain dom node in this case not possible anymore

**Comment by henrikbjorn** [comment]
@taion I am not sure i understand because to me it seems like Overlay composes my Child with a Position element (https://github.com/react-bootstrap/react-overlays/blob/master/src/Overlay.js#L52) which contains the positioning props that is needed. Otherwise i am not sure how using Overlay would position my child correctly.

**Comment by jquense** [comment]
@henrikbjorn Position then needs to inject the props you are seeing to your component so that it knows how to position itself. Specifically: `placement`, `arrowOffsetLeft`, `arrowOffsetTop`, `positionLeft`, `positionTop`

**Comment by dkulichkin** [comment]
@taion could you please explain one more time how to use react-bootstrap/react-overlays Overlay component without having the warning:

```Warning: Unknown props `placement`, `arrowOffsetLeft`, `arrowOffsetTop`, `positionLeft`, `positionTop` on <div> tag```

I use it as following along with last versions of react-bootstrap and react itself:

```<Overlay show={show} onHide={(e) => this.hide(e)} placement="bottom" container={this} className="popover-container">Content</Overlay>```

and still having that warning

Thanks a lot

**Comment by jquense** [comment]
@dkulichkin look at how Popover and Tooltip are implemented in react-bootstrap

**Comment by yoobit** [comment]
@dkulichkin you will need to create your own custom overlay, you can do the following according to the react documentation. Then wrap that inside a OverlayTrigger. 

<div style={{
                                  position: 'absolute',
                                  backgroundColor: '#EEE',
                                  boxShadow: '0 5px 10px rgba(0, 0, 0, 0.2)',
                                   border: '1px solid #CCC',
                                   borderRadius: 3,
                                   marginLeft: -5,
                                   marginTop: 5,
                                   padding: 10
                  }}
>{yourStaffHere}</div>

**Comment by godmar** [comment]
I'm getting the same warning after upgrading code that uses OverlayTrigger to the latest React and react-bootstrap (0.30.5). I could use advice.

Old code:
```
  return (
    <OverlayTrigger placement='right' overlay={tooltip}>
      <Link to={props.href} className={joinClasses(classes)}>
        <FontIcon name={props.icon} className='side-navbar-icon' />
        {text}
      </Link>
    </OverlayTrigger>
```

Triggers warning, but works.

New code?

**Comment by yoobit** [comment]
One quick question, is the return being called by another overlay?

for example:
```
class CustomOverlay extends React.Component {
render() {
return (...);
};
}
<Overlay>
 <CustomOverlay />
</Overlay>
```

**Comment by agile116** [comment]
So this warning is unable to removed in using react-overlays?

**Comment by yoobit** [comment]
```
 return (
    <OverlayTrigger placement='right' overlay={tooltip}>
      <Link to={props.href} className={joinClasses(classes)}>
        <FontIcon name={props.icon} className='side-navbar-icon' />
        {text}
      </Link>
    </OverlayTrigger>
```

create a custom component for <Link>

```
export default 
(
{
children = [],
to = null,
className = null,
replacement = null,
arrowOffsetLeft = null,
arrowOffsetTop = null,
....(whatever else that's unknown)
}
) => {
return ( <Link to={to} className={className}>
{children}
<Link>
};

```

replace <Link> with the custom link you just created. Not a great way to get around these warning.

**Comment by benmonro** [comment]
@jquense is there any plan to fix this warning?

**Comment by benmonro** [comment]
The library produces errors when it's used as documented. Forgive me for
not agreeing, but somewhere between this and/or react-overlays an invalid
prop is being passed to a div which causes the error.

**Comment by jquense** [comment]
you are responsible for dealing with the props injected by the overlay trigger, per the above advice check out how we handle this with the react bootstrap tooltip and popover, both of which do not warn.

**Comment by benmonro** [comment]
Ah ok. Well might want to update the docs to reflect that.

**Comment by Sutikshan** [comment]
This could get fixed, if we can update `isBsProp()` of `utils/bootstrapUtils.js` as below

```
function isBsProp(propName) {
  const bsProps = [
    'bsClass',
    'bsSize',
    'bsStyle',
    'bsRole',
    'positionLeft',
    'positionTop',
    'arrowOffsetLeft',
    'arrowOffsetTop',
  ];
  return bsProps.includes(propName);
}
```

**Comment by taion** [comment]
No. Those props are _supposed_ to get passed down. They're what make tooltips and popovers work.

**Comment by siddy2181** [comment]
Any solution to this one yet?

**Comment by benmonro** [comment]
@siddy2181 the react-bootstrap team said that these are not the warnings you are looking for.  https://gph.is/1W9lKoB
![image](https://user-images.githubusercontent.com/399236/51129717-083f7380-17e0-11e9-96db-b2c6967b895f.png)
