### ISSUE TITLE
Repository stilled maintained?

### ISSUE THREAD

**Issue by floriangosse** [react-bootstrap/react-overlays#1033]
I wonder if the project is still maintained. There are many open unanswered issues.

In a project I'm working on we heavily use the `react-overlays` but have some problems we can't solve by ourselves and would need some changes in the library. But because there is not much activity on the project we haven't posted any issue yet.

If this project isn't actively maintained anymore we should put a note in the README and add links for some alternatives.

**Comment by jquense** [comment]
This project is not maintained anymore it's been superceded by restart-ui which has all the same functionality and more. I'd recommend switch to that package name, it's a direct evolution of this codebase

**Comment by floriangosse** [comment]
Thanks for the update. I think to make it clear that this repository was superseded by restart-ui this information should be put into the README and the repository should be archived.

This should make it easier for users to find what they want and get some more interaction on restart-ui.

**Comment by jquense** [comment]
added a note 👍 thanks for the suggestion
