### ISSUE TITLE
Placing Affix inside scrollable container

### ISSUE THREAD

**Issue by krambertech** [react-bootstrap/react-overlays#108]
Hi!

Is there a way to place `<Affix />` inside scrollable container. So it will listen to container's `onscroll` events rather than `window`.

Thanks in advance :)

**Comment by jquense** [comment]
set the `container` prop to the scrollable container I believe.

**Comment by taion** [comment]
Right now we only calculate offset to viewport (i.e. `window`). We'd be happy to take a PR to expand that functionality, but we don't really consider it a missing feature right now. I'm not sure it's easily possible given that AFAIK `fixed` is relative to viewport, not to scroll parent.

**Comment by taion** [comment]
Well, the TWBS v3 one doesn't do that. If you use `position: absolute` you end up having to either re-parent the affix or re-calculate the offset on every scroll update – neither seem really ideal.

**Comment by jquense** [comment]
agreed they aren't ideal, this sort of thing is way more complicated then it should be, which i guess is why `position: sticky` is a thing :P
