### ISSUE TITLE
AutoAffix multiple childrens

### ISSUE THREAD

**Issue by olegshilov** [react-bootstrap/react-overlays#110]
I was faced with next problem. When I'm trying to pass multiple components to AutoAffix
```
<AutoAffix viewportOffsetTop={80} container={this}>
  <UserFilter
    value={this.props.criteria}
    onChange={this.handleCriteriaChange}
  />
  <LinkContainer to="/users/new">
    <Button bsStyle="success" block>Create User</Button>
  </LinkContainer>
</AutoAffix>
```
I get the following error:
<img width="266" alt="screen shot 2016-08-22 at 15 37 18" src="https://cloud.githubusercontent.com/assets/930121/17854921/5cc1287c-687e-11e6-8a4a-e079a58ce63e.png">

This code works as expected:
```
<AutoAffix viewportOffsetTop={80} container={this}>
  <div>
    <UserFilter
      value={this.props.criteria}
      onChange={this.handleCriteriaChange}
    />
    <LinkContainer to="/users/new">
      <Button bsStyle="success" block>Create User</Button>
    </LinkContainer>
  </div>
</AutoAffix>
```

Perhaps worth adding `children: React.PropTypes.node` to PropTypes to be able to add more then one component without wrapping them once again in a useless div.

**Comment by jquense** [comment]
> Perhaps worth adding children: React.PropTypes.node to PropTypes to be able to add more then one component without wrapping them once again in a useless div.

The propType isn't the issue, its that this component only works with one child, which is why it throws a hard error when you have more than one. It's not possible to affix multiple children in the way you are excepting.
