### ISSUE TITLE
Refs Must Have Owner Warning

### ISSUE THREAD

**Issue by rafgugi** [react-bootstrap/react-overlays#120]
I keep getting warning

> Uncaught Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).

that makes my app error. After spending days to search the problem, I found Modal.js have `ref={'modal'}`. I think that using ref to select a specific component should be avoided. 

The warning shown after the modal showed.
here is the stack trace:
```

invariant
addComponentAsRefTo
attachRef
ReactRef.attachRefs
attachRefs
notifyAll
close
closeAll
perform
batchedMountComponentIntoNode
perform
batchedUpdates
batchedUpdates
_renderNewRootComponent
_renderSubtreeIntoContainer
renderSubtreeIntoContainer
_renderOverlay
Portal_componentDidMount
(anonymous function)
measureLifeCyclePerf
(anonymous function)
notifyAll
close
closeAll
perform
perform
perform
flushBatchedUpdates
closeAll
perform
batchedUpdates
batchedUpdates
dispatchEvent
```

**Comment by rafgugi** [comment]
I use react-router. then I use react-bootstrap/lib/modal that has dependency on this.

**Comment by jquense** [comment]
hi there, this error is almost always actually caused by having two instances of React in your bundle somehow. I can confirm that the ref usage in this particular case is corect some i'm failry certain that the problem is duplicate Reacts for you.
