### ISSUE TITLE
AutoAffix doens't work with custom React components

### ISSUE THREAD

**Issue by calvinwyoung** [react-bootstrap/react-overlays#121]
Copying the sample code from the [example page](https://react-bootstrap.github.io/react-overlays/#affixes), the `<AutoAffix>` helpers works correctly with this code:

```jsx
class AffixExample extends React.Component {
  render() {
    return (
      <div className='affix-example'>
          <AutoAffix viewportOffsetTop={15} container={this}>
              <div className='panel panel-default'>
                  <div className='panel-body'>
                      I am an affixed element
                  </div>
              </div>
          </AutoAffix>

          <div style={{height: "4000px"}} />
      </div>
    );
  }
}

ReactDOM.render(<AffixExample />, mountNode);
```

However, if I move the `panel` into a separate React component, then the `<AutoAffix>` no longer toggles `position: fixed` on its child element:

```jsx
class CustomElement extends React.Component {
  render() {
    return (
      <div className='panel panel-default'>
          <div className='panel-body'>
              I am an affixed element
          </div>
      </div>
    );
  }
}

class AffixExample extends React.Component {
  render() {
    return (
      <div className='affix-example'>
          <AutoAffix viewportOffsetTop={15} container={this}>
              <CustomElement />
          </AutoAffix>

          <div style={{height: "4000px"}} />
      </div>
    );
  }
}

ReactDOM.render(<AffixExample />, mountNode);
```

I couldn't find anything that explicitly mentioned this behavior in the docs — is there something else we need to do to get this working for custom components?

**Comment by jquense** [comment]
you need to forward the props injected by the Affix to a DOM node

**Comment by calvinwyoung** [comment]
Got it, that makes sense — thanks for the clarification.

**Comment by vijayranghar** [comment]
@jquense @calvinwyoung Could you please elaborate `you need to forward the props injected by the Affix to a DOM node`? I'm facing the same issue

**Comment by antzhdanov** [comment]
> @jquense @calvinwyoung Could you please elaborate `you need to forward the props injected by the Affix to a DOM node`? I'm facing the same issue

Just wrap your custom component with another div so that Affix could apply styles to it instead of trying to pass props to your custom component:
```
<Affix>
  <div>
    <YourCustomComponent/>
  </div>
</Affix>
```
