### ISSUE TITLE
lastFocus is updated even when autoFocus is false

### ISSUE THREAD

**Issue by digitaltoad** [react-bootstrap/react-overlays#123]
This causes the last element to be focused even if `autoFocus` is `false`. I'm not sure if this is by design or not but the code updates `lastFocus` in `checkForFocus` and `focus`. Should there be a configuration flag for`restoreLastFocus`?

**Comment by jquense** [comment]
this is intention I'm not sure why you would want to disable this, otherwise focus will be dropped completely from the page which is no good for a11y

**Comment by digitaltoad** [comment]
Given the case where you would want to focus a different element on hide conditionally, unless I'm not looking at the problem correctly, it would require both a handler for `onHide` and a handler for `onExit`. This also means that focus bounces twice.

**Comment by taion** [comment]
Care to PR this?

**Comment by taion** [comment]
resolved by https://github.com/react-bootstrap/react-overlays/pull/145
