### ISSUE TITLE
Create TypeScript typings

### ISSUE THREAD

**Issue by aaronbeall** [react-bootstrap/react-overlays#126]
This project doesn't seem to have any TypeScript typings.

**Comment by taion** [comment]
The project maintainers don't use TypeScript, so we're not going to do this. Feel free to contribute your own to DefinitelyTyped, or follow up with https://github.com/react-bootstrap/react-bootstrap/issues/1921.

**Comment by aaronbeall** [comment]
Initial stab at it here:

https://github.com/aaronbeall/DefinitelyTyped/blob/master/react-overlays/react-overlays.d.ts

What wasn't clear to me is what parts of `react-overlays` are already exposed by `react-bootstrap`.
