### ISSUE TITLE
AutoAffix stick at bottom

### ISSUE THREAD

**Issue by agungsb** [react-bootstrap/react-overlays#128]
Hi again,

I've seen the example and it works pretty good to stick the element to the top. But, is it possible to make it stick to the bottom?

I have a left nav consists of several elements which is scrollable until it reaches the last element. If such condition is met, then it will 'lock' the whole left nav to the bottom.

**Comment by alexcastillo** [comment]
Was there a resolution here?

**Comment by krupatel** [comment]
@agungsb How were you able to solve this?
