### ISSUE TITLE
Feature Request: Add support for `backdrop` in `Overlay` component

### ISSUE THREAD

**Issue by EvNaverniouk** [react-bootstrap/react-overlays#131]
It would be great if the `Overlay` component could support a backdrop like the `Modal`. The main reason is that in my case I want to have popovers/tooltips with a backdrop and `Modal` doesn't support positioning relative to another element.

**Comment by jquense** [comment]
I don't think we'll add this to overlay, but its' definitely doable with the Modal (I know because i've done it), if you combine it with the Position component

**Comment by taion** [comment]
I agree. The backdrop implies certain modal semantics that don't fit in the context of a general-purpose overlay.

**Comment by EvNaverniouk** [comment]
> ...but its' definitely doable with the Modal ... if you combine it with the Position component

I feel silly for not trying this first. `<Modal><Position>...</Position></Modal>` does exactly what I need. Thanks for the tip.
