### ISSUE TITLE
Use `show` instead of `in`

### ISSUE THREAD

**Issue by khankuan** [react-bootstrap/react-overlays#133]
Hi, noticed that the prop is named as `in`. Thought that it might be better to be named as `show` to keep consistency with other components like `Modal`. More importantly, `in` is a keyword which causes linter to error out.

**Comment by taion** [comment]
React transition group uses "enter" and "leave" for the transition controls, so "in" feels like the most appropriate name here. If your linter is having issues, that's on you – ESLint with the React plugin does not hit these issues, as far as I've seen.

**Comment by jquense** [comment]
yeah, in is a bit annoying in code, but its (i think) less confusing, since `show` implies "visible" which may not be related to the animation applied.

**Comment by khankuan** [comment]
@jquense you're right, show is misleading. Would something like `active` be another alternative? @taion i dont think react plugin does anything with `in`. This repo does not hit the problem because its using `props.in`.
