### ISSUE TITLE
Transition vs ReactCSSTransitionGroup

### ISSUE THREAD

**Issue by khankuan** [react-bootstrap/react-overlays#134]
Hi, thanks for providing a declarative way to handle animations on overlays. I was trying out the `Transition` component by hot swapping the css that im using in `ReactCSSTransitionGroup`. I've noticed that the behavior seems to be quite different. In `ReactCSSTransitionGroup`, when an item is to performEnter, the `enter` className is applied and the `enter-active` is immediately applied right after. In `Transition`, the `enter-active` class is only applied based on transitionEnd. Thus, if `enter-active` only gets applied after timeout, taking double the time to transit. Wonder if anyone else has encountered the same issue before.

Cheers :)

**Comment by taion** [comment]
These are really meant to mimic how the Bootstrap transitions work. Use `enteringClassName` instead of `enteredClassName` if you want something applied immdeiately.
