### ISSUE TITLE
Modal animation changes

### ISSUE THREAD

**Issue by ps18** [react-bootstrap/react-overlays#140]
Modal loads from top by default.
Is there any way to change the modal animation?
Is it possible to slide from Right to left?Could you please help me with an example?
Need to apply the changes to a single modal, not to all modals in the application.

**Comment by jquense** [comment]
modal animation Is all handled by css transitions, you can change the animation by adjusting the css. We 9nly have the one animation that bootstrap defines but you are free to change it via css

**Comment by ps18** [comment]
Thank you so much @jquense .
I was able to achieve with css.
