### ISSUE TITLE
How to tell the difference between click and esc close?

### ISSUE THREAD

**Issue by TheBox193** [react-bootstrap/react-overlays#141]
With `<Overlay />` Is there a way to tell the difference of how the close callback got called? Specifically between a click and pressing the esc key?

https://github.com/react-bootstrap/react-overlays/blob/master/src/RootCloseWrapper.js#L84
https://github.com/react-bootstrap/react-overlays/blob/master/src/RootCloseWrapper.js#L90

It seems odd to me that nothing is passed to the callback. No string, nor the DOM event to work with.

For my use case
* Pressing `esc` means cancel & close.
* Clicking on background means save & close.

**Comment by taion** [comment]
Feel free to add PR that passes through the event or something

**Comment by jquense** [comment]
I think there is even an open PR for that pending
