### ISSUE TITLE
Prevent adding aria-hidden attribute on the rest of the document content when Modal is opened

### ISSUE THREAD

**Issue by cosminnicula** [react-bootstrap/react-overlays#147]
Automatically adding aria-hidden attribute on the rest of the document content when Modal is opened causes some regressions with my existing CSS.

Is there a way to prevent this behavior?

Thanks!

**Comment by jquense** [comment]
you can mess with the ModalManager instance for the modal, to not do it. I'd fix the problem from the other end though, having css that's selecting on `aria` attributes sounds like a bad idea, and the behavior of the Modal in adding those attributes is the correct one.

**Comment by cosminnicula** [comment]
"mess" - you mean actually modifying the source code of the ModalManager.js file? that would be really hackish.

Indeed, adjusting the CSS selector to not care about `aria-` attributes is a good practice, but not always a solution, especially if that piece of code sits inside an internal library which is consumed by others.

Regarding the behavior of the Modal on adding `aria-` attributes, from an a11y perspective I would say it's not mandatory for compliance with the WAI-ARIA specs https://www.w3.org/TR/wai-aria-practices-1.1/#dialog_modal, and that's because you:
1. either have all the elements reachable via keyboard and therefore the body decorated with role="application". In this case, AFAIK the virtual cursor is disabled and aria-hidden redundant
2. or have only some elements reachable via keyboard, for which aria-hidden=true would actually behave correctly

Adding aria-hidden in both cases is a bit obtrusive.

**Comment by jquense** [comment]
ModalManager is pluggable on Modals so you can provide a custom one, Agreed that is is more code than you'd want to write though.

We probably aren't going to allow opting out of the `aria-hidden` behavior easily. It's a well accepted best practice for JS modals. Nothing else on the page should be accessible via the keyboard, mouse or virtual cursor.
