### ISSUE TITLE
iOS fires onscroll event only after you've stopped scrolling.

### ISSUE THREAD

**Issue by PierreGUI** [react-bootstrap/react-overlays#148]
Hey guys, great work with react-overlays 👍 

I'm running into an issue with affixed components on iOS: because they "_think different_" in the way they handle the `scroll` event.
([source 1](http://stackoverflow.com/questions/2863547/javascript-scroll-event-for-iphone-ipad), or [source 2](https://www.tjvantoll.com/2012/08/19/onscroll-event-issues-on-mobile-browsers/))

In Affix.js#L36 should you listen for `touchmove` as well as `scroll`? Hope that's enough to solve the issue.

Cheers

**Comment by PierreGUI** [comment]
My bad it seems the information I get is **outdated** and therefore **inaccurate**.
So can someone explain why affixed components wait for scroll (momentum) to stop before behaving?

As far as I can see on my components and yours, it is not working on iOS 😰

**Comment by victsant** [comment]
I am having the same issue did anyone get to figure out how to fix this?

**Comment by taion** [comment]
Many browsers now debounce scroll events and render event handlers passive to prevent jank on mobile.

This is consistent with how the affix scroll listeners work in Bootstrap, so I think this is okay for now. You might be better off with a `position: sticky` polyfill.
