### ISSUE TITLE
Overlay onHide doesn't detect right click

### ISSUE THREAD

**Issue by rogyvoje** [react-bootstrap/react-overlays#157]
I have a use case where I want to hide Overlay when user clicks right click outside of the overlay, is it possible to create something like that?

For now onHide method on Overlay component does not detect right click, and it does not execute the given function...

**Comment by taion** [comment]
use `rootClose`

**Comment by rogyvoje** [comment]
@taion that does not help, that property accepts only bool values, I just wanna know why right click is not detected as a click outside of the Overlay component?

**Comment by jquense** [comment]
@taion looks like we block modified and right clicks: https://github.com/react-bootstrap/react-overlays/blob/master/src/RootCloseWrapper.js#L85

**Comment by jquense** [comment]
I'm not sure we want to support it tho on overlays...

**Comment by taion** [comment]
I see – I don't think we should support right clicks.

**Comment by jquense** [comment]
I'd be happy to support it in RootCloseWrapper if anyone wants to PR it, but I agree that Overlay shouldn't support it
