### ISSUE TITLE
RootCloseWrapper doesn't work on iOS Safari

### ISSUE THREAD

**Issue by ursatong** [react-bootstrap/react-overlays#158]
Looks like `RootCloseWrapper` only supports mouse click and key events. Touch the screen won't close the overlay.

**Comment by taion** [comment]
Appears to be some bug with how `<RootCloseWrapper>` works with iOS Safari.

**Comment by ReactGirl** [comment]
https://github.com/react-bootstrap/react-bootstrap/issues/1906

**Comment by jquense** [comment]
this should be fixed in v1
