### ISSUE TITLE
Support for CSS Modules styleName for renderBackdrop on <Modal />?

### ISSUE THREAD

**Issue by reywright** [react-bootstrap/react-overlays#161]
https://github.com/gajus/react-css-modules#whats-the-problem

To quickly describe, the way CSS Modules works is you import a css file into your react application, and then you can reference the classes with `styleName`.

These classes are name spaced based on the component, THEN get put on className. There's a lot of benefits to this approach but it's outside the scope of this ticket.

I noticed that renderBackdrop doesn't expand styleName. For reference, if I do the following:

```
<Modal
    styleName="centered" />
```

It will expand the proper className:

```
<div data-reactroot="" role="dialog" class="CustomComponent__centered__368Yp">
```

but renderBackdrop does not: 
```
<div class="">
```

**Comment by jquense** [comment]
The `styleName` thing is a react-css-modules addition, not plain ol css-modules and webpack. I'm not at all sure how any why react-css-modules does that but It's almost certainly a limitation on their end. Why not just do it the normal way?

```
import styles from './mycss.css'
...
<div className={styles.myClass}>

`

**Comment by reywright** [comment]
That's probably true but I think most people are using the react-css-modules addition with it if they are using it in a react application. I linked to the issues with using it the normal way but I'll list them out here:

* You have to use camelCase CSS class names (for example. you can't do styles.vertical-centered)
* You have to use styles object whenever constructing a className (verbose)
* Mixing CSS Modules and global CSS classes is cumbersome
* Reference to an undefined CSS Module resolves to undefined without a warning.

I think a lot of people should be not creating css style sheets beholden to javascript syntax and such, so that's why the library is pretty good. Why I'm making the ticket is mostly because they automatically do this on all "elements". Maybe it's because the renderBackdrop is a function rather than an element?

**Comment by jquense** [comment]
I'm a user of css-modules in a bunch of apps, and I don't find those points super convincing. Point 1 is actually incorrect, webpack will convert style names to camelCase so you can write them normally but refer to them in camelcase. Points 2-3 are easily handled by `classnames` module. 

In any case, those are just my personal opinions and you are welcome to use whatever you like :) However, if it doesn't work in this case, it's a problem with that library, i'd file the bug there, there isn't much I can do.

**Comment by reywright** [comment]
I think the thing I'm trying to understand is why renderBackdrop is asking for a function rather than an element. I think that's the part that's messing up as that's very non standard. Why would it be a function? I do have a couple of responses for though regarding what you said.

So with the classnames modules, you can of course do the following: 

```cx(styles.blah, styles.foo)```

and that's fine and works as expected, but what about this:

```
cx(styles.blah, styles.foo, {
   styles.float: this.props.isBar
}) 
```

So `classnames` can take variables that represent css module classes, but if you try to pass an object with conditional values, all of a sudden you can't do this, as you can't do `styles.float: this.props.isBar` as that's invalid. I can't think of a single way to pull this off without using styleName. I also do think having to repeat styles.[foo] is a bit verbose and I was looking at the source wondering why you guys were using `classnames` just to resolve simple css module stuff...

It's not that I think this is requesting special functionality... I just think the way the interface is designed here unless I'm missing something, breaks expected operability. Could the backdrop maybe optionally accept an element?
