### ISSUE TITLE
createClass is deprecated in React 15.5

### ISSUE THREAD

**Issue by JeffreyATW** [react-bootstrap/react-overlays#162]
Replace all createClass calls with ES6 classes. If no one's working on this, I can take a swing at it.

**Comment by JeffreyATW** [comment]
Here's my PR: #163

**Comment by gabor** [comment]
any news on this one? or would a PR which just switches to the `create-react-class` module have a better chance?

**Comment by orther** [comment]
I believe all we need is a version bump now.

**Comment by bryancr89** [comment]
@orther  Wondering when are you going to bump the version?
