### ISSUE TITLE
Update for 15.5 deprecations 

### ISSUE THREAD

**Issue by bigkrp** [react-bootstrap/react-overlays#165]
Update for 15.5 deprecations 

I have warning for Transition module.
more info https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

Related issue https://github.com/react-bootstrap/react-bootstrap/issues/2550

**Comment by jharris4** [comment]
The PR to fix createClass warnings seems to have addressed the prop-types warnings as well:

https://github.com/react-bootstrap/react-overlays/pull/163
