### ISSUE TITLE
Release the latest?

### ISSUE THREAD

**Issue by aatrostle** [react-bootstrap/react-overlays#170]
While upgrading for 15.5 I noticed this package had been recently updated but the latest build was failing. I submitted #168 to fix the build and shortly after that was merged #162 was closed. With those changes this lib should be ready for React 15.5 correct?

**Comment by jquense** [comment]
thanks we will release when we get a moment

**Comment by dlong500** [comment]
I see v0.7.0 was released, but it looks like react-bootstrap is still pulling in v0.6.12 even with a clean install.  Do we need another release of release of react-bootstrap with updated dependencies to get it to pull in the new version?
