### ISSUE TITLE
Transition doesn't appear to be honoring timeout for exiting => exited state transition.

### ISSUE THREAD

**Issue by KevinJ90825** [react-bootstrap/react-overlays#174]
I have a Transition object with a timeout of 5 seconds. On entering, the calls go `onEnter` `onEntering` `[Sleep 5 seconds]` `onEntered`. On exiting, the calls skip the sleep of 5 seconds between `onExiting` and `onExited`.

Any tips on how to get around this?

**Comment by taion** [comment]
We've since moved the transition implementations out of this library.
