### ISSUE TITLE
Auto change placement of Position when overlapped by the browser window

### ISSUE THREAD

**Issue by Masalovych** [react-bootstrap/react-overlays#178]
Hi guys,

We have a bug that tooltip overlapped by browser window. See screenshot.
Can it be possible to change "calculatePosition" method (in calculatePosition.js) to return also "placement" value. And if "overlayNode" doesn't fit in the browser windows then change "placement " to opposite value (left <-> right or top <-> bottom).

<img width="353" alt="screen shot 2017-06-08 at 09 49 40" src="https://user-images.githubusercontent.com/6996140/26915821-45792e26-4c30-11e7-8451-ce8c54c805b7.png">

Best Regards,
Dmytro

**Comment by ravisuryawanshi18** [comment]
@Masalovych  Got solution on this?

**Comment by Masalovych** [comment]
@ravisuryawanshi18 As I remember, we decided to use our custom tooltip.

**Comment by jquense** [comment]
Popperjs is used for positioning now and can handle these cases and Overlay supports the `flip` prop now to enable that behavior
