### ISSUE TITLE
0.8.0 should be 1.0.0

### ISSUE THREAD

**Issue by EvHaus** [react-bootstrap/react-overlays#189]
The 0.8.0 release actually contains some breaking changes as users will now need to:

- Migrate to using `react-transition-group` for the `Transition` component, and
- Remove `enteredClassName`, `enteringClassName`, `exitedClassName`, `exitingClassName` props on the `Transition` component and migrate to using a children function instead (https://github.com/react-bootstrap/react-overlays/commit/4e5183d0583b7dba944fee7a9b9c2de4721bba6e#diff-3daf91d0ab759c5dcc40965696b7ed84R56) and
- Remove `backdropTransitionTimeout` and `dialogTransitionTimeout` from the `<Modal />` components and add `timeout` to the `Transition` component instead

These steps weren't included in the CHANGELOG, so it was a bit of a surprise when a minor version upgrade broke a bunch of our components. It would be great if the library's version would reflect those breaking changes by doing a major version bump.

Hope this request doesn't come across as snarky. Just wanted to make a recommendation to ease the upgrade progress for other users.

**Comment by taion** [comment]
By convention, minor version bumps before 1.0.0 do include breaking changes. This convention is broadly used throughout the Node community, and in fact is what is implemented with the `^` version range with npm.

**Comment by taion** [comment]
We'd welcome improvements to the changelog, though!

**Comment by jquense** [comment]
yes the changelog omissions are a mistake on my part. feel free to PR a fix
