### ISSUE TITLE
Do onEnter/onExit work for an Overlay without a Transition component?

### ISSUE THREAD

**Issue by cgilboy** [react-bootstrap/react-overlays#190]
The docs seem to indicate that I can use `onEnter`/`onExit` as props on an Overlay object to find out when it will enter/exit the view, but I don't seem to have luck doing so. I was able to hack something together by assigning a `Transition` to the Overlay, but then I was unable to dynamically set the `onEnter`/`onExit` functions. What is the correct way to use these lifecycle-ish functions?

Thanks!

**Comment by taion** [comment]
They only work with animations; those are the animation callbacks. Since you're controlling `show` on an `<Overlay>` yourself, you don't need those callbacks.
