### ISSUE TITLE
How do we implement affix.

### ISSUE THREAD

**Issue by tatsujb** [react-bootstrap/react-overlays#193]
There is no description of how to do this anywhere. the Demo just says "oh use the ```<Affix>``` tag and maybe throw in an ```<AutoAfix>```"

well I've tried this:
```
<AutoAffix>
<Affix>
<Menu/>
</Affix>
</AutoAffix>
```

it doesn't even compile

**Comment by tatsujb** [comment]
do you mean this : https://react-bootstrap.github.io/react-overlays/#affixes it's what I quoted the first time.

if this is your idea of a "doc" then it's intentionally vague

**Comment by jquense** [comment]
There is literally a description of the type, name and shape of entire API (props) accompanied by a working, _live editable_, example of the component demonstrating exactly how it works in practice and the code required to do it. That's above and beyond what 90% of OSS projects provide for documentation. If you want more examples I'd suggest perusing the tests.
