### ISSUE TITLE
npmjs.com package out of date

### ISSUE THREAD

**Issue by jeffredodd** [react-bootstrap/react-overlays#199]
Hello, its been 25 days since we merged the accessibility fix in #195. Is it possible to get a new release cut for https://www.npmjs.com/package/react-overlays ? Thanks in advance!

**Comment by taion** [comment]
Thanks for the reminder. Should this be v0.8.1 or v0.9.0? The latter would require a React-Bootstrap version bump as well.

**Comment by jeffredodd** [comment]
I believe this change was not considered breaking as we kept support for the `keyUp` handler as well as `keyDown` but moved the closing of modal to `keyDown`. So I'd guess `0.8.1`?

**Comment by taion** [comment]
If someone complains I guess we can back it out :p

**Comment by taion** [comment]
released v0.8.1
