### ISSUE TITLE
Documenting Initial API changes

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-overlays#2]
I've had to change a few of the api's (mostly in Modal) to make some of them work in a more generic setting. Ultimately any path forward migrating RB proper to this, will need to at least be aware of these changes in order to adjust the inevitable wrappers we need to write there.

I'd also definitely love feedback on these decision.

**modal**
- `dialogTransitionTimeout` and `backdropTransitionTimeout` props added instead of the static constants
- `animation` renamed to `transition` and only accepts a `Transition` component (false by default)
- `onBackdropClick`, 'onEscapeKeyUp` added as a hooks (This was more added for another of my projects)
- `backdropStyle` and `backdropClassName` were added instead of BootstrapMixin
- similarly `containerClassName` was added instead o just adding `modal-open`
- this __styles the container node directly with `overflow: hidden`__ this seemed preferable then making the user provide a class or shipping css with it, since this is actually a big feature of the Modal
- Modal DOM layout always has a wrapping div (instead of just when there is a backdrop)
- No padding of the modal dialog when open (since that is a bootstrap specific component)

**Position**
- `container` also accepts a function
- empty arrowOffsets are now `undefined` instead of `null`, lets them work with es6 default values
- __not done but thinking about it__ rename the injected arrow props, to something more descriptive and generic?

**Portal**
- `container` also accepts a function

**Overlay**
- `animation` renamed to `transition` and only accepts a `Transition` component (false by default)

**Comment by taion** [comment]
I never fully understood the transition durations on `Transition` - is this in case the transitioning node changes identity as the transition is playing? It'd be nice if this could be optional in the general case.

This all sounds really cool, though!

**Comment by jquense** [comment]
Its not if the node changes identity its if it it mutated in a way that triggers a reflow/repaint, the end event [just won't fire](http://labs.silverorange.com/files/webkit-bug/). Since the Transition component _depends_ on the callbacks firing in order to maintain its internal state machine we need to ensure that they are always fired, the specified duration is really actually a timeout; a "if you don't hear anything from the node after X then just move on".

Maybe we should jsut rename it to timeout, that does seem clearer, the "duration" name comes straight from upstream bootstrap

**Comment by taion** [comment]
I may be misunderstanding, but the bug there seems more restricted than that, and only applies to edge cases with e.g. setting `display: none`. Unless I'm doing something wrong, I see that in e.g. [in this CodePen where I mess with parent height](http://codepen.io/anon/pen/rVoJYz) that the transition end event still fires properly.

I wonder if we can't just default the timeouts to `undefined` or `null`, and only use them when they're explicitly specified. I expect that this should work just fine for most users, no?

**Comment by jquense** [comment]
I am not super familiar with all the cases where the bug happens it but its also fairly random across browsers as well.

We can default it to undefined but I am a little concerned about the Transition component getting into bad states it can't recover well from. If it doesn't break anything i don't care that much, tho I seen this "fix" in a bunch of places, bootstrap, jquery, [zepto](https://github.com/madrobby/zepto/blob/master/src/fx.js#L107), so I am a bit wary to just remove it. perhaps someone has more info?

I'll test it out a bit without them, tho I need to adjust the component a bit to allow that.

**Comment by taion** [comment]
You're probably right. I think all this means in practice is that you can default the timeout to a high value, and have it really be a "just-in-case" thing... maybe.

**Comment by cesarandreu** [comment]
Setting a default value seems like a good idea. That looks like it's what [ngAnimate](https://github.com/angular/angular.js/blob/master/src/ngAnimate/animateCss.js#L867-L872) does, although it seems they try to get more precise timing information... It's probably more of a failsafe, so stuff doesn't totally break on shitty browsers.

**Comment by PeteJodo** [comment]
Just an fyi, the docs for Portal and Modal (at least, only looked at those) don't mention a `show` prop yet when you look at the code for it you can see it being used. I haven't actually used it yet but I'm assuming it does expect the `show` prop.

**Comment by taion** [comment]
These seem to all be documented now, and R-B uses R-O now, so I think this is resolved.
