### ISSUE TITLE
Possible problem with new document.scrollingElement behavior in Chrome 61?

### ISSUE THREAD

**Issue by joekrill** [react-bootstrap/react-overlays#200]
I'm not totally sure if this is actually an issue, or something I'm doing wrong -- or potentially it's an issue in `dom-helpers`? I'm having trouble getting to the root of the problem so perhaps someone else will have some insight. 

The ultimate problem is that in Chrome 61 my popovers are suddenly positioning incorrectly when I'm not scrolled to the top the page (the appear much farther below the element than they should). This seems to only happen when my `Popover`'s `container` prop returns `document.scrollingElement` (or `document.documentElement`, which is the same thing).  

My understanding is that Chrome -- as of version 61 -- has changed the behavior of `document.scrollingElement` to return `document.documentElement` instead of `document.body` to match the CSSOM spec (see [Chrome 61 release notes](https://blog.chromium.org/2017/08/chrome-61-beta-javascript-modules.html)). I think this change is what is causing the issue. (`document.scrollingElement` is usually the `html` element, not the `body`).

If I've scrolled from the top of the page, `document.scrollingElement.scrollTop` will return the vertical scroll position -- but `document.body.scrollTop` will still return 0.  So I believe this causes the popover position to be overshot by `document.scrollingElement.scrollTop` pixels.

The workaround I'm using for now is to return `document.body` instead of `document.scrollingElement`, but that doesn't seem like the correct solution (though perhaps I'm wrong). I'm also using the [`scrollparent`](https://www.npmjs.com/package/scrollparent) package to determine the parent element. It seems like the position should still be calculated correctly even when it's given a container that is `document.scrollingElement`.

**Comment by mgol** [comment]
If this Chrome change caused an issue in a particular app or library, most likely it already had this issue in Firefox where `document.scrollingElement` has been `document.documentElement` from the beginning. Therefore, apps/libraries that handled this correctly in all popular browsers shouldn't be affected.

**Comment by taion** [comment]
I'm not seeing this on Chrome 63. Can you reproduce this on e.g. the components page here?

**Comment by taion** [comment]
As far as I can tell, we haven't had any problems, so I'm going to close this out for now.

**Comment by aminsmartsense** [comment]
Same issue is coming in latest version. @joekrill You are right.
