### ISSUE TITLE
From what I understand

### ISSUE THREAD

**Issue by touqeerkhan11** [react-bootstrap/react-overlays#209]
From what I understand the builtin Transition was causing some issues and it was removed from the repo in favor of react-transition-group 2, but the docs weren't updated and now I am thinking why react bootstrap is not using the later version of react-overlays (which was updated 3 months ago apparently) and the whole modal thing is not really working with react 16 too, and there aren't any good examples to add transitions with react-transition-group, so my question is if this repo even maintained¿

**Comment by jquense** [comment]
yes it is. if you wnat to speed things along PR's are the best way to get stuff done. thanks!
