### ISSUE TITLE
Not working, close the modal on press escape key in IE11

### ISSUE THREAD

**Issue by og24715** [react-bootstrap/react-overlays#210]
I doubt this commits  67d06fd92b7ecb29477fd39eea8767ba16242762.
Because KeyboardEvent.key is 'Esc', not 'Escape' in IE11, so you need to look at KeyboardEvent.keyCode.

<img width="1237" alt="rbesc" src="https://user-images.githubusercontent.com/8489199/31266161-7317a3a4-aaad-11e7-8b79-ac664b83b4d1.png">

**Comment by taion** [comment]
Ah, I forgot this wasn't a React event.

**Comment by og24715** [comment]
Thanks for your quick response and for your wonderful work! （╹◡╹）
