### ISSUE TITLE
smaller builds with tree shaking

### ISSUE THREAD

**Issue by cainlevy** [react-bootstrap/react-overlays#212]
We're looking at depending on `react-overlays` to implement our Modal and Popover components, but have no need for Affix. According to `webpack-bundle-analyzer`, bundling without Affix would save around 40% on the compressed size of the `react-overlays` dependency.

Are there any plans to create an ES2015 entry point with [`pkg.module`](https://github.com/rollup/rollup/wiki/pkg.module)?

**Comment by taion** [comment]
We might at some point, but tree shaking isn't super reliable and we don't really recommend it, nor do we rely on it ourselves.

Instead, just import from `react-overlays/lib/Whatever` directly.

**Comment by cainlevy** [comment]
> tree shaking isn't super reliable and we don't really recommend it, nor do we rely on it ourselves.

Ah, we're finding it quite useful! The benefits have been valuable.

> Instead, just import from react-overlays/lib/Whatever directly.

Will investigate.
