### ISSUE TITLE
Modals with input are broken with pull request #208 in React 15

### ISSUE THREAD

**Issue by bunkscene** [react-bootstrap/react-overlays#217]
Hey guys,

When my project upgraded to react-overlays 0.7.3, my modals with input forms all broke.  When I change the value of an input field, the component is rendering.  It seems that every time the component renders, you are calling a focus() on the modal.  So when I tab out of my field, instead of tabbing into the next field, the focus goes to the modal form and I lose the input focus.

As far as I can tell, this code in Modal.js is the culprit:

```
  onPortalRendered = () => {
    this.focus();

    if (this.props.onShow) {
      this.props.onShow();
    }
  }
```

I don't know if something different happens in 16, but I am using 15 and this is causing a problem.  The old code only called focus onShow.  Why did this change?

So far, my only solution is to set autoFocus=false and enforceFocus=false, but I am not sure if that is ideal.

Thanks,
Dave

**Comment by taion** [comment]
How is that getting called, though? `onPortalRendered` only gets called the first time the portal mounts, so this shouldn't be causing issues unless something else is going wrong.

Do you have a runnable repro?

**Comment by taion** [comment]
cc @jquense I think this is a bug: https://github.com/react-bootstrap/react-overlays/blob/685a743f9e6fcf28ad40593ef2431a402fb15fd7/src/LegacyPortal.js#L77-L88

`this.props.onRendered` there gets called every time the `<Portal>` renders, not just the first time.

**Comment by bunkscene** [comment]
Ok, here is the repro:

[https://github.com/bunkscene/react-bootstrap-modal-issue](https://github.com/bunkscene/react-bootstrap-modal-issue)

**Comment by stephanebarbey** [comment]
I'm bitten by that bug too. Is there a workaround (that does not involve setting enforceFocus to false, as that would break another component (react-tinymce))?

Thanks.
