### ISSUE TITLE
React 16 compatible release

### ISSUE THREAD

**Issue by ntucker** [react-bootstrap/react-overlays#223]
https://github.com/react-bootstrap/react-overlays/commit/37b2e0d506d0cad1cbfd60bcc6750d6f84359ca9 appears to fix some issues with React 16. It would be lovely if we could have an npm release. :)

**Comment by taion** [comment]
Waiting on https://github.com/react-bootstrap/react-overlays/pull/218 and https://github.com/react-bootstrap/react-overlays/pull/222

**Comment by taion** [comment]
Released.
