### ISSUE TITLE
Refs on elements in Portal are not usable in parent componentDidUpdate in React 16

### ISSUE THREAD

**Issue by taion** [react-bootstrap/react-overlays#224]
Ref https://github.com/react-bootstrap/react-bootstrap/issues/2841

This is a regression introduced here with the change to the React 16 portal API. With the new portal API, the contents of the portal don't actually get mounted until after the parent finishes rendering, so refs there aren't available in `componentDidUpdate` on the parent.

To resolve this, I think we actually need to do the DOM stuff around the portal when rendering the component initially in React 16.

**Comment by gaearon** [comment]
>With the new portal API, the contents of the portal don't actually get mounted until after the parent finishes rendering

Can you expand on that or maybe provide a small fiddle? I would expect child portal to provide same timing guarantees as a regular child.

**Comment by taion** [comment]
@gaearon 

It's a regression here, not in React. In the old implementation we would call `ReactDOM.unstable_renderSubtreeIntoContainer` in `componentDidMount`:
https://github.com/react-bootstrap/react-overlays/blob/1335c50a8e168cfdc2642ef7f22319ffc4e35ee8/src/LegacyPortal.js#L30-L33
https://github.com/react-bootstrap/react-overlays/blob/1335c50a8e168cfdc2642ef7f22319ffc4e35ee8/src/LegacyPortal.js#L70-L93

In the new implementation, we kept the logic of mounting the portal node in `componentDidMount`, but of course then we need to render again to have it available in `render` for `ReactDOM.createPortal`:
https://github.com/react-bootstrap/react-overlays/blob/1335c50a8e168cfdc2642ef7f22319ffc4e35ee8/src/Portal.js#L32-L35
https://github.com/react-bootstrap/react-overlays/blob/1335c50a8e168cfdc2642ef7f22319ffc4e35ee8/src/Portal.js#L53-L57

This is sort of an inconvenience to the API, since previously we could just do stuff in `componentDidMount` and not have to sniff for the availability of DOM APIs in `componentWillMount`, and things are probably going to be a bit awkward with SSR, but the React APIs are working as designed as far as I'm aware.

**Comment by gaearon** [comment]
I feel a bit silly, but why can't `this._portalContainerNode` be created *before* the component renders for the first time?

**Comment by taion** [comment]
That would be the fix – where possible, create the portal container node before rendering `<Portal>` for the first time.

**Comment by gaearon** [comment]
Oh got it. Thanks for talking me through it. Yes, that’s the right fix I think.
