### ISSUE TITLE
Portal: Warning: owner-based and parent-based contexts differ

### ISSUE THREAD

**Issue by epeli** [react-bootstrap/react-overlays#23]
Just a heads up as everything seems to work as expected. I get the following warning

    Warning: owner-based and parent-based contexts differ (values: `[object Object]` vs `undefined`) for key (store) while mounting Connect(MyOriginalComponent) (see: http://fb.me/react-context-by-parent)

when I mount a component connected to a Redux store using [connect][c] to a `Portal` (in my case using the `Overlay`).

I'm using React 0.13.x.

[c]: https://github.com/rackt/react-redux#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

**Comment by jquense** [comment]
yup this is expected. context crosses portal boundaries oddly in react 0.13 that causes this warning. It isn't indicative of any real problem, and will go away without any issue in react 0.14

**Comment by epeli** [comment]
Cool.

**Comment by epeli** [comment]
Reopening. My app broke on React 0.14 RC. The warning is gone but the context is not passed correctly. Error message is from Redux is:

    Uncaught Error: Invariant Violation: Could not find "store" in either the context or props of "Connect(LegacyRoleSelector)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(LegacyRoleSelector)".

**Comment by jquense** [comment]
are you using a version of react-overlays that works with react 0.14? Our prelease is not compatible with the new RC yet

**Comment by epeli** [comment]
Oh, didn't realize there was a branch for the 0.14 release. Will try it.
