### ISSUE TITLE
Event bubbling through portals is a breaking change

### ISSUE THREAD

**Issue by mcoetzee** [react-bootstrap/react-overlays#236]
Hi there,

We've been using `<Modals />` liberally  in our app, and the switch to use React's new portal has broken our app in many places. Click handlers are being fired in the components that launched the modal when clicking anywhere on the modal (due to https://reactjs.org/docs/portals.html#event-bubbling-through-portals).

I'm trying to think of a scenario where this is desirable and I'm coming up short. If this event bubbling is desirable for some modal use cases, then shouldn't this behaviour be an opt-in as opposed to the non-configurable default (in order to make this a non-breaking change)?

**Comment by taion** [comment]
There’s nothing we can do about this. That’s just how portals work in React 16. React doesn’t offer a way to opt out of this. You can work around this on your side if needed by e.g. having a different component handle rendering the actual modal, but short of that we have no way of genetically preventing events from bubbling through the portals.

**Comment by hedgepigdaniel** [comment]
Its still a breaking change - at least the change that introduced the usage of react portals should have been a major version bump, or there should have been a major version bump where the peer dependency on react changed from `^15.0.0` to `^16.0.0`.
