### ISSUE TITLE
Using sideEffects in package.json

### ISSUE THREAD

**Issue by OriR** [react-bootstrap/react-overlays#241]
As of webpack 4 there's a way to mark components with the [`sideEffects`](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) property in the `package.json`.

`react-bootstrap` itself is already marked with [`sideEffects: false`](https://github.com/react-bootstrap/react-bootstrap/blob/17a3cdda1c4d8b00b26f2412bfb282e0a3c47faf/package.json#L10) so it would be nice to have this marked as well :)

**Comment by MeghaMehrotra** [comment]
@OriR  I am raising a PR for this:)
