### ISSUE TITLE
Multiple modals: on closing the second opened modal, the first one also disappears

### ISSUE THREAD

**Issue by abhimrawks** [react-bootstrap/react-overlays#250]
I have 2 modals on a screen invoked through 2 different sources.

At a time, both modals are present in the DOM (I have checked in console). **But on clicking on close icon on the second modal (which was visible till now), the first modal also disappears.**

On checking the HTML DOM in console, I observed the reason as the first modal updating its opacity to 0.

Before Second Modal close is clicked:
`react-overlays-modal__body--open .react-overlays-modal-portal {
    opacity: 1;
}`

After Second Modal close is clicked:
`.react-overlays-modal-portal {
    opacity: 0;
    transition: all 0.2s;
}
`

**Previous Issue**
Earlier I was passing `enforceFocus: true`. But I started to have issues `Maximum call stack size exceeded enforceFocus`. So  I have updated it to `enforceFocus: false` which has resolved the maximum call stack issue.

**Other props:**
`autofocus: true`

**Environment:**
react: 16.2.0
react-overlays: 0.8.3
Browser: Chrome Version 66.0.3359.181

**Comment by taion** [comment]
Take a look at the examples with `ModalManager` for dealing with multiple modals.

**Comment by abhimrawks** [comment]
@taion I could not find examples of `ModalManager` anywhere, plus there is no mention of it in the documentation. Can you please point me towards a specific relevant example?
