### ISSUE TITLE
using OverlayTrigger with Popover cant manually hide this.

### ISSUE THREAD

**Issue by againksy** [react-bootstrap/react-overlays#260]
i have tried to show it like
`this.refs.overlay.show()`
when the
`<Overlay show={true} ref="overlay" trigger="click" rootClose={false} placement="bottom" overlay={`
it is showing , but i unable to hide this=(

**Comment by taion** [comment]
you control whether it shows based on the prop. use state to manage shown state and do e.g. `show={this.state.show}`
