### ISSUE TITLE
Bug: custom overlay won't close when pressing `esc` button or clicking outside (once having focus)

### ISSUE THREAD

**Issue by yairEO** [react-bootstrap/react-overlays#266]
Go here:
http://react-day-picker.js.org/examples/input-custom-overlay

1. (Mouse) click on the datepicker input, an "overlay" should show.
2. Click on any *white* area within the overlay, then press the <kbd>esc</kbd> key
3. Overlay should close, but nothing happens
4. Click anywhere *outside* of the overlay, and again the overlay should close but it's not.

This also happens when giving focus to the custom input within the overlay in the demo page.

**Comment by jquense** [comment]
I think you have the wrong repo? this looks like a bug with react-day-picker
