### ISSUE TITLE
[Accessibility]The BaseModal carries role=dialog by default would cause that the dialog title is announced twice

### ISSUE THREAD

**Issue by Otobelikethee** [react-bootstrap/react-overlays#268]
Why does the BaseModal set extra role=dialog (see the first role=dialog on div outside)?
It causes that the dialog title is announced twice by screen reader.

![image](https://user-images.githubusercontent.com/12393817/46137304-e7c4cb00-c27b-11e8-8bd7-fe744c9bba5c.png)

### Reproducible Version
* macOS High Sierra Version 10.13.4 (17E199)
* VoiceOver Version 8 (562.18.4)
* Safari Version 11.1 (13605.1.33.1.2)

**Comment by Otobelikethee** [comment]
@jquense Could you please to explain this confusing issue?

**Comment by Otobelikethee** [comment]
@jquense Thank you for your reply.

**Comment by jquense** [comment]
should be fixed in v1
