### ISSUE TITLE
Allow warning 4.x

### ISSUE THREAD

**Issue by ekohl** [react-bootstrap/react-overlays#269]
Warning 4.x is out. The breaking changes are a license change and internals. Updating it shouldn't cause issues.

**Comment by jquense** [comment]
happy to take a PR updating yeah!

**Comment by ekohl** [comment]
Do you prefer `^4.0.0` or a more permissive `>= 3.0.0 < 5.0.0`?

**Comment by jquense** [comment]
4.0.0 should be fine
