### ISSUE TITLE
Portal causes controlled input cursor position to jump to the last character

### ISSUE THREAD

**Issue by D1plo1d** [react-bootstrap/react-overlays#27]
Adding an input inside a portal that has a ReactLink back to the top level component (above the portal) causes the cursor to jump to the last character after ever keystroke.

I think this is happening because Portal render's it's children in a separate React.render call.

I couldn't find any docs on ReactUpdate.asap() which is used in the ReactDOMInput component to control updating the field but it seems like it's only waiting for batch updates from the components inside the current React.render call.

**Comment by D1plo1d** [comment]
@jquense Why was this issue closed?

**Comment by jquense** [comment]
Sorry thought there was a comment.  

I can't repo this behavior but I am familiar with the problem. Asynchronous value updates will reset the cursor position. the asap calls in the react inputs are there specifically to address this problem when using the portal pattern. If it is suddenly not working then that is an upstream regression. In any case there is nothing we can do to address it, you might want to open an issue with React if you can demonstrate the regression.

**Comment by D1plo1d** [comment]
Ok, thanks for the info.
