### ISSUE TITLE
How to use the transition prop in Modal?

### ISSUE THREAD

**Issue by carlosrberto** [react-bootstrap/react-overlays#28]
I have the following code:

```javascript
import React from "react";
import { Transition, Modal } from "react-overlays";

class DocumentModal extends React.Component {
    static propTypes = {
        show: React.PropTypes.bool
    }

    static defaultProps = {
        show: false
    }

    renderModal() {
        return (
            <div className="document-viewer">
             ....
            </div>
        );
    }

    render() {
        let { show } = this.props;

        let transition = <Transition in={show} timeout={150} className='fade' enteredClassName='in' enteringClassName='in' />

        let modal = (
            <Modal
                show={show}
                backdropClassName="document-viewer-backdrop"
                className="document-viewer"
                transition={transition}
            >
                {this.renderModal()}
            </Modal>
        );

        return modal;
    }
}

export default DocumentModal;

```

but returned the following error:

```
Warning: Failed propType: Invalid prop 'transition' of value '[object Object]' supplied to 'Modal'. Expected an Element `type`, not an actual Element Check the render method of `DocumentModal`.
```

**Comment by jquense** [comment]
the prop expects a component type not an element you need to wrap that transition up in something like MyTransition and pass that to the modal. you can take a look at the react-bootstrap overlay component and Fade transition as an example

**Comment by carlosrberto** [comment]
Thanks @jquense, it works!

**Comment by reywright** [comment]
@jquense what do you mean by "wrap that transition up in something like *MyTransition*"? I don't quite follow...  are you saying to just wrap the Modal with the Transition component?

**Comment by jquense** [comment]
@reywright check out what we do in React-bootstrap: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Modal.js#L191

**Comment by c0d3ster** [comment]
@jquense I am getting this error when trying to implement a Fade transition for my Modal component:
"Error: React.Children.only expected to receive a single React element child."
I'm solely using react-overlays for my project, and the Modal works fine without the transition component.  Here is the code for my Fade component:
`import React from 'react';
import {Transition} from 'react-overlays';

var Fade = React.createClass({
	render() {
		return(
			<Transition
				in={false}
			  	timeout={500}
			  	mountOnEnter={false}
  				unmountOnExit={false}
  				transitionAppear={false}
  				className="fade"
				enteringClassName="in"
				enteredClassName="in"
			/>
		);
	}
});

export default Fade;`

I even tried to put in some of the default values just to be sure it would work as expected, but I can't seem to get past this error.  Here is the relevant portion of my code for the Modal:
`        return (
            <div className="full-container">
                <Modal show={this.state.showModal} onHide={this.hideModal} backdropClassName="modal-backdrop" className="modal-container" transition={Fade}>
                    <div className="modal-content">        
                        <div className="modal-header">
                            <h2>Your Functions</h2>                   
                        </div>
                        <div className="modal-body">
                            {localFns ? 
                                Object.keys(this.props.localFnsDisplay).map(function(fn , i) {
                                    var obj = localFns[fn];
                                    //var newStr = fn.string.replace(/\n/g,<br/>);
                                    var newStr = obj.string.split(/\n/g);
                                    return (
                                        <div key={i}>
                                            <br/>
                                            <button onClick={this.testClick} data-fn={obj.string}>{obj.name}</button>
                                            <br/>
                                            {newStr.map(function(line, i) {
                                                var indent = '12px';
                                                if (i == 0) indent = '0px';
                                                return(<p style={{marginLeft: indent}} key={i}>{line}</p>);
                                            })}
                                        </div>);
                                }.bind(this))
                            : null}
                        </div>
                        <div className="modal-footer">
                            <button onClick={this.hideModal} className="middle-button">Close</button>
                        </div>
                    </div>
                </Modal>`
 I can give more of the component code if it would be pertinent to the issue, but I didn't want to overload you with code when the rest of the component works properly.  I think it's something to do with setting in to false instead of passing it as a prop, but I'm not sure how to do that with the way I'm passing the Fade component in as a prop to the Modal.  I can't find anyone else with this issue though so I'm not sure what the actual issue is...  Thanks in advance for taking a look at this.

**Comment by c0d3ster** [comment]
still can't get the transition working, but I guess this issue thread is dead...

**Comment by jquense** [comment]
I'd suggest looking at how Fade on modals is implemented in real t bootstrap

**Comment by c0d3ster** [comment]
Don't you think I already did that considering the comment before mine says the exact same thing? My code is copied from the Bootstrap fade code, just without as many props.  I wouldn't have taken the time to post two long blocks of code if I didn't look at how it was implemented in bootstrap first...

My updated (but still not working) code for the Fade component is:


```
import React from 'react';
import {Transition} from 'react-overlays';

var Fade = React.createClass({
	render() {
		return(
			<Transition
				in={false}
			  	timeout={500}
			  	mountOnEnter
  				unmountOnExit
  				transitionAppear
  				className="fade"
				enteringClassName="in"
				enteredClassName="in"
			/>
		);
	}
});

export default Fade;
```

Looking at the React DOM when I initiate the modal pop up, it looks as if two Fade elements are created for some reason and the content is never inserted into the modal (although the backdrop does load w/o a Fade).

**Comment by jquense** [comment]
>  just without as many props

there's your problem right there. The error you are getting is REALLY clear, transition expects a child and you didn't provide one

**Comment by c0d3ster** [comment]
what do you mean I didn't provide a child?  I thought the entire Modal is the child of the Transition component?  The React Overlays documentation says to simply put the Transition component in as the prop to the Modal and that's exactly what I did.

**Comment by jquense** [comment]
`children` props don't magically get passed through components you Fade component swallows it

**Comment by c0d3ster** [comment]
so are you saying that I need to call this.props.children within my Fdde component?  I'm not understanding why that's the case when the Bootstrap code for Fade.jsx doesn't have any props for the children of the modal...

**Comment by jquense** [comment]
It does: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Fade.js#L72

I'd suggest maybe getting more familiar with common prop passing patterns in React. Your issue isn't related to this component, but with understanding how props propagate through react components

**Comment by c0d3ster** [comment]
I understand how spread syntax works.  My point is that the example from React-Bootstrap is too complex to gain the basic understanding of how the code handles the Transition component prop.  The example on transitions from react overlays instead directly inserts the content as the child of the Transition component, but there is no basic sample implementation of a modal with a Transition component prop attached.  I'm not asking you to implement my Fade for me, I'm trying to figure out where the children prop comes from within the Modal component.

**Comment by jquense** [comment]
The react-bootstrap Fade component is 12 lines of code minus propTypes; there is no logic in it either. I don't think that counts as "complex", it is the simplest possible example of how to implement a custom Transition component.

The Modal uses that component [here](https://github.com/react-bootstrap/react-overlays/blob/master/src/Modal.js#L274-L287)

There is no additional logic to use it with a Modal, you are simply not passing the children through to the underlying transition component. copy and paste the the Fade component, inspect it and tweak it until it does what you want

**Comment by c0d3ster** [comment]
ahh okay thank you.  Having the source to see how overlays handles the Transition was helpful.  Also, I meant that the Modal component was complex, not the fade component.  I understand that the Modal for React-Bootstrap needs to be versatile, but it would be nice to have a simple example of a fading modal in the overlays examples as well.
