### ISSUE TITLE
Body element should not be required at import time

### ISSUE THREAD

**Issue by nip3o** [react-bootstrap/react-overlays#283]
I'm tying to migrate from react-overlays 0.8.3 to 1.1.1, but after upgrading to the newer version we run into the following crash when our webpack bundle loads:

    TypeError: document.body is null[Learn More] vendors.2966214b0af6eeb1dc74.js line 3642 > eval:21:7
        scrollbarSize webpack:///./node_modules/dom-helpers/util/scrollbarSize.js?:21
    ModalManager2React	js http://localhost:8000/static/assets/system/vendors.2966214b0af6eeb1dc74.js:4644
        __webpack_require__ http://localhost:8000/static/assets/system/bundle.084924a405a4fa2f81d5.js:84
        <anonymous> webpack:///./client/system/components/base/modal/modal.tsx?:14
        tsx http://localhost:8000/static/assets/system/bundle.084924a405a4fa2f81d5.js:1502
        __webpack_require__ http://localhost:8000/static/assets/system/bundle.084924a405a4fa2f81d5.js:84
        <anonymous> webpack:///./client/system.js?:365
        <anonymous> webpack:///./client/system.js?:2
        js http://localhost:8000/static/assets/system/bundle.084924a405a4fa2f81d5.js:922
        __webpack_require__ http://localhost:8000/static/assets/system/bundle.084924a405a4fa2f81d5.js:84
        checkDeferredModules http://localhost:8000/static/assets/system/bundle.084924a405a4fa2f81d5.js:46
        <anonymous> http://localhost:8000/static/assets/system/bundle.084924a405a4fa2f81d5.js:219
        <anonymous> http://localhost:8000/static/assets/system/bundle.084924a405a4fa2f81d5.js:1

This is because the `script` tag that loads our bundle is located in `head`, so `body` does not exist at import time. Since styles and other libs are depending on being loaded before `body`, moving the bundle is not an option. Instead I believe this code should run after the page has finished loading?

**Comment by taion** [comment]
this might be a bug, but you should not in general load your JS bundle until after your page has finished loading anyway

**Comment by nip3o** [comment]
The main reason why we are doing that is since we are using `css-loader` to load our CSS with webpack, so importing the bundle after page load will render a page completely without styling for a short while unless loading the bundle before `body`. I agree that, for example, trying to render a modal before document has loaded would be a misuse, but not just importing the module.

**Comment by jquense** [comment]
not to turn this into a critique of your build setup, but that also sounds less than ideal, css-loader should only be used to dynamically load styles in development, ideally you'd want to extract to css files for a real build which would be loaded normally in your html.

That said, it also sounds like you might have a race condition, there isn't any reason to think that b/c you loaded the js before the body all the css will finish loading before rendering starts, you may just be getting lucky with the timing.

That's all off topic tho, if there is a bug it would be in `dom-helpers` happy to take a PR there if you want to address it for this util

**Comment by taion** [comment]
i think the bug here is that we construct a `ModalManager` on import in `Modal`, and that doing so attempts to read the scroll bar size

**Comment by nip3o** [comment]
Would it be possible to just defer the construction of `ModalManager` until page has loaded or until the first `Modal` is created, or is it more complicated than that?

**Comment by taion** [comment]
i think we should, yeah. or perhaps use react context here?

**Comment by taion** [comment]
Fixed in #297
