### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by nip3o** [react-bootstrap/react-overlays#294]
It's been a while and a couple of bug fixes since the latest release, maybe it's time for a new one?

**Comment by bpas247** [comment]
@taion @jquense how do we feel about this? We're currently experiencing a block for `react-bootstrap` at this [PR](https://github.com/react-bootstrap/react-bootstrap/pull/3563) because we haven't published a new release yet.

Is there anything left we should do before releasing the next version?

**Comment by jquense** [comment]
#299

**Comment by jquense** [comment]
we could maybe release a prerelease v3 tho here

**Comment by nip3o** [comment]
@jquense the popper PR is merged now, any more stuff that we need to wait on?

**Comment by mxschmitt** [comment]
Maybe we can release our first version with semantic-release once #372 is merged.

**Comment by boxfoot** [comment]
@bpas247 it's been tagged here in the repo, but hasn't been published to [npm](https://www.npmjs.com/package/react-overlays) 

![image](https://user-images.githubusercontent.com/487130/64871574-1f529180-d60b-11e9-9614-d3038a846544.png)

But ye: Given that the release has been tagged here, and the code as tagged is working for me in my fork, it seems like publishing would be pretty easy.

**Comment by TrySound** [comment]
@boxfoot 
![image](https://user-images.githubusercontent.com/5635476/64871745-8e9da500-d64e-11e9-97d8-d288a4baf4ba.png)

**Comment by bpas247** [comment]
Closing this now as the new release was published 😃
