### ISSUE TITLE
Fix Codecov Reporting

### ISSUE THREAD

**Issue by mxschmitt** [react-bootstrap/react-overlays#305]
Mostly the same as here has to be done in the current repo: https://github.com/react-bootstrap/react-bootstrap/issues/3864

**Comment by bpas247** [comment]
So looking at the diffs for the project setups of React-Bootstrap and React-Overlays,
https://github.com/react-bootstrap/react-bootstrap/blob/b36d2614234221771f9d0bfe98ac1a024e551c28/.babelrc.js#L31-L33
Seems to be doing the same thing as
https://github.com/react-bootstrap/react-overlays/blob/1cd98d8dc332e9ae4fa8a9d9fe0b2a398beb2f61/.babelrc.js#L21-L25
although I could be wrong about that.
