### ISSUE TITLE
chore: Update dependencies (Dependabot integration?)

### ISSUE THREAD

**Issue by bpas247** [react-bootstrap/react-overlays#310]
After running `yarn outdated`:
![image](https://user-images.githubusercontent.com/18705892/61167574-228bad00-a4f6-11e9-8339-648f20718d09.png)

Should we just go ahead and integrate Dependabot to this repo?

**Comment by TrySound** [comment]
It's very annoying
https://twitter.com/sindresorhus/status/1149923077737742337

**Comment by mxschmitt** [comment]
> It's very annoying
> https://twitter.com/sindresorhus/status/1149923077737742337

But that's the GitHub Security Feature. It creates automated PRs Independent if you are using Dependabot.

**Comment by taion** [comment]
done now!
