### ISSUE TITLE
Uncaught TypeError: (0 , _uncontrollable.default) is not a function

### ISSUE THREAD

**Issue by MarkEmerson** [react-bootstrap/react-overlays#333]
issue: Uncaught TypeError: (0 , _uncontrollable.default) is not a function

**packages:**
react-dom: 16.8.6
react:16.8.6
react-overlays:1.2.0

**still getting this error:** 

browser source:
Uncaught TypeError: (0 , _uncontrollable.default) is not a function

var UncontrolledDropdown = (0, _uncontrollable.default)(Dropdown, {
  show: 'onToggle'
});

browsewr console output:
Uncaught TypeError: (0 , _uncontrollable.default) is not a function
    at Object../node_modules/react-bootstrap/node_modules/react-overlays/Dropdown.js (Dropdown.js:305)
    at __webpack_require__ (bootstrap 5aa110fbdd7b2189a480:680)
    at fn (bootstrap 5aa110fbdd7b2189a480:105)
    at Object../node_modules/react-bootstrap/es/Dropdown.js (app.5aa110fbdd7b2189a480.js:105655)
    at __webpack_require__ (bootstrap 5aa110fbdd7b2189a480:680)
    at fn (bootstrap 5aa110fbdd7b2189a480:105)
    at Object../node_modules/react-bootstrap/es/index.js (app.5aa110fbdd7b2189a480.js:110277)
    at __webpack_require__ (bootstrap 5aa110fbdd7b2189a480:680)
    at fn (bootstrap 5aa110fbdd7b2189a480:105)
    at Object.<anonymous> (TooltipWrapper.jsx:2)
client?843a:38 [WDS] Hot Module Replacement enabled.

we do not directly use the uncontrolled component, it is being used by react-overlays in the Dropdown component.

anything i may be missing? and do i need to open a new issue for the same problem?

_Originally posted by @MarkEmerson in https://github.com/react-bootstrap/react-overlays/issues/300#issuecomment-515867172_

**Comment by TrySound** [comment]
Check please which version do you have here
node_modules/react-overlays/node_modules/uncontrollable/package.json
or here
node_modules/uncontrollable/package.json

**Comment by MarkEmerson** [comment]
> Check please which version do you have here
> node_modules/react-overlays/node_modules/uncontrollable/package.json: **node_modules only contains folders classnames and warning. it does not contain uncontrolled**
> or here
> node_modules/uncontrollable/package.json : **version 6.0**

**Comment by TrySound** [comment]
Ok. Now try to remove react-overlays and install it again. This will update transitive dependencies.

**Comment by MarkEmerson** [comment]
oddly after removing and re-installing react-overlays: react-overlays isnt updating its node_modules and only folders warning and classnames exist. im stumped at this one.

**Comment by TrySound** [comment]
Ah, try to reinstall bootstrap too. It has another version which is not matched with yours.

**Comment by MarkEmerson** [comment]
yes i think that is the issue. seems i have installed react-overlays directly under reat-bootstrap - my bad. trying now...

**Comment by MarkEmerson** [comment]
uninstalled react-overlays from the wrong location (under react-bootstrap) and installed under correct location (under top level node_modules). successful

**Comment by michelekc** [comment]
I am still having issues with this. I have uninstalled react-bootstrap and react-overlays and then reinstalled react-overlays and react-bootstrap. Here are my versions:
react-bootstrap ^1.0.0-beta.9
react-overlays ^1.2.0

**Comment by caioaletrocadock** [comment]
there is some solution? I'm still getting the same error and tried everything

**Comment by TrySound** [comment]
Try this `yarn add react-overlays@next`

**Comment by caioaletrocadock** [comment]
> Try this `yarn add react-overlays@next`

It didn't work and it throws more errors about not found dependencies inside react-overlays

**Comment by KartaviK** [comment]
I have same problem. I use webpack to compile project. Compiling ends successful but i catch this error in browser console
```
Dropdown.js:365 Uncaught TypeError: (0 , _uncontrollable.default) is not a function
    at eval (Dropdown.js:365)
    at Object.../node_modules/react-overlays/Dropdown.js (vendors.bundle.js:1268)
    at __webpack_require__ (bundle.js:786)
    at fn (bundle.js:151)
    at eval (Dropdown.js:8)
    at Module.../node_modules/react-bootstrap/esm/Dropdown.js (vendors.bundle.js:944)
    at __webpack_require__ (bundle.js:786)
    at fn (bundle.js:151)
    at eval (Header.tsx:16)
    at Module../components/Header.tsx (bundle.js:965)
```

**Comment by KartaviK** [comment]
> I have same problem. I use webpack to compile project. Compiling ends successful but i catch this error in browser console
> 
> ```
> Dropdown.js:365 Uncaught TypeError: (0 , _uncontrollable.default) is not a function
>     at eval (Dropdown.js:365)
>     at Object.../node_modules/react-overlays/Dropdown.js (vendors.bundle.js:1268)
>     at __webpack_require__ (bundle.js:786)
>     at fn (bundle.js:151)
>     at eval (Dropdown.js:8)
>     at Module.../node_modules/react-bootstrap/esm/Dropdown.js (vendors.bundle.js:944)
>     at __webpack_require__ (bundle.js:786)
>     at fn (bundle.js:151)
>     at eval (Header.tsx:16)
>     at Module../components/Header.tsx (bundle.js:965)
> ```
> 
> webpack.conig.js:
> 
> ```js
> const path = require("path");
> const HtmlWebpackPlugin = require("html-webpack-plugin");
> 
> module.exports = {
>     entry: './index.js',
>     context: path.join(__dirname, 'src'),
>     devServer: {
>         host: 'localhost',
>         publicPath: "/",
>         contentBase: "./build",
>         watchContentBase: true,
>         noInfo: false,
>         hot: true,
>         inline: true,
>         historyApiFallback: true,
>         port: 8087,
>         stats: {
>             colors: true
>         }
>     },
>     output: {
>         path: path.join(__dirname, "/build"),
>         filename: "bundle.js",
>         chunkFilename: './[name].bundle.js'
>     },
>     resolve: {
>         modules: [
>             path.resolve('./src/*'),
>             path.resolve('./node_modules'),
>         ],
>         alias: {
>             '~': path.resolve('./src'),
>         },
>         extensions: ['.js', '.es6', '.jsx', '.ts', '.tsx',],
>     },
>     module: {
>         rules: [
>             {
>                 test: /\.tsx?$/,
>                 use: [
>                     "babel-loader",
>                     "awesome-typescript-loader",
>                 ],
>             },
>             {
>                 test: /\.(js|jsx|es6)$/,
>                 exclude: /(node_modules|bower_components)/,
>                 use: 'babel-loader',
>             },
>             {
>                 test: /\.css$/i,
>                 use: ["style-loader", "css-loader"]
>             },
>             {
>                 test: /\.(png|jpg)$/,
>                 exclude: /node_modules/,
>                 use: 'file-loader?name=[name].[ext]',
>             },
>         ]
>     },
>     plugins: [
>         new HtmlWebpackPlugin({
>             template: "./templates/index.html",
>             favicon: './favicon.ico',
>         }),
>     ],
>     optimization: {
>         splitChunks: {
>             cacheGroups: {
>                 vendor: {
>                     test: /node_modules\/.*/,
>                     name: 'vendors',
>                     chunks: 'all',
>                 },
>             },
>         },
>     },
> };
> ```
> 
> If i remove `import Dropdown from 'react-bootstrap/Dropdown` - it will work

Well, my solution it is just removing react-bootstrap from project...

**Comment by shijiezhou1** [comment]
Getting same error: 
const redisAdapter = socket_io_redis_1.default({ host: 'localhost', port: 6379 });
                                              ^

TypeError: socket_io_redis_1.default is not a function

**Comment by TrySound** [comment]
@shijiezhou1 Not related to this project.

**Comment by ajay767** [comment]
i m getting this error while using parcel.js

`bundle.js:233 Uncaught TypeError: (0 , _test.default) is not a function
    at Object.parcelRequire.index.js../test (bundle.js:233)
    at newRequire (bundle.js:47)
    at bundle.js:81
    at bundle.js:120`

to resolve this issue use  `import { testing } from './test';` instead of `import testing from './test';`
