### ISSUE TITLE
Transition can fail if new props affect animation state

### ISSUE THREAD

**Issue by jquense** [react-bootstrap/react-overlays#40]
Ran into this writing some Tabs stuff. Essentially as you switch tabs you apply an `'active'` class that sets the display to `block` this needs to happen _before_ the `in` class is added to the element to start the animation.

As it stands transitions triggered from a prop change actually start happening _before_ the new props are flushed to the DOM. ie triggered here: https://github.com/react-bootstrap/react-overlays/blob/master/src/Transition.js#L50-L63

my thought is that we need to move these calls to componentDidUpdate. 

cc @taion

**Comment by taion** [comment]
Frickin' React and animations.
