### ISSUE TITLE
`Uncaught TypeError: node.removeAttribute is not a function` with multiple modals

### ISSUE THREAD

**Issue by jesenko** [react-bootstrap/react-overlays#41]
Example (adapted from official react-overlay modal example, with two modals at same level): 
https://gist.github.com/jesenko/e453679c1f1579bd5127

On close, error is thrown at `node.removeAttribute('aria-hidden');` in `react-overlays/lib/utils/manageAriaHidden.js`

**Comment by jesenko** [comment]
Modifying https://github.com/react-bootstrap/react-overlays/blob/master/src/Modal.js#L164 from
`let setMountNode = ref => this.mountNode = (!ref || ref.getMountNode());`
to
`let setMountNode = ref => this.mountNode = (ref && ref.getMountNode());`
fixes it for me, not sure about other consequences though...

**Comment by donatasbacius** [comment]
+1
