### ISSUE TITLE
onWindowScroll never called

### ISSUE THREAD

**Issue by LKay** [react-bootstrap/react-overlays#44]
On Chrome the `scroll` event attached to `window`is never called and element positioning is never updated. Event is supposedly attached to the global `window` object but when I tried to debug it the callback function is never called (breakpoint below).

![Debug](https://s3.amazonaws.com/f.cl.ly/items/3k1m2G0m19300v2l0R40/Image%202015-11-26%20at%201.50.47%20PM.png)

**Comment by taion** [comment]
Which version? And does http://react-bootstrap.github.io/react-overlays/examples/#affixes work for you?

**Comment by LKay** [comment]
Example page works for some reason. But when I basically copy-paste the code it doesn't work locally. My version in `node_modules` is 0.5.4.

**Comment by LKay** [comment]
I'm using `react-bootstrap` in my app. I have fixed top `NavBar` component, two columns layout (sidebar, main content). The content of the main container looks pretty much like the following (simplified the original code) if that helps.

```javascript
<Row>
    <Col md={ 4 }>
       Some sidebar
    </Col>
    <Col md={ 8 }>
            <Row>
                <Col xs={ 12 }>
                    <AutoAffix affixClassName="filter-fixed" container={ this }>
                        <Well>
                            Some affixed content
                        </Well>
                    </AutoAffix>
                </Col>
            </Row>
            <Row>
                <Col xs={ 12 }>
                    Here goes main content
                </Col>
            </Row>
     </Col>
</Row>
```

**Comment by taion** [comment]
That's close to the layout that the React-Bootstrap docs page uses. Is it rendering in an `<iframe>` or something?

**Comment by LKay** [comment]
After much debugging I found the reason. The element which should be affixed was a child of element with absolute positioning and `overflow: auto` CSS property. When I change the container to be positioned relatively the scroll event is fired. 

I'm not sure if it's correct behavior or a bug (looks like bug) as it doesn't calculate the offset properly as the window isn't technically scrolled but the container element. The `AutoAffix` component has `container` property but as I see in the code the scroll event is binded to `window` element anyway. I believe that could be fixed by attaching `onscroll` event to the container element (if not present then to `window`).

**Comment by taion** [comment]
What? No - fixed positioning is _always_ relative to the viewport, so the equivalent of an affix on an internally scrolling component doesn't make sense. As documented, the point of the affix both here and in e.g. TWBS is to toggle `position: fixed`.
