### ISSUE TITLE
More placement types for Position

### ISSUE THREAD

**Issue by vladimir-rovensky** [react-bootstrap/react-overlays#52]
Would it be possible to add more placement types for the `Position` component? It works great, but I can only position in one dimension, the other gets centered (e.g. placement=bottom means essentially bottom center).

Ideally, the `Position` component would have a similar API to that of [jQuery UI Position](https://jqueryui.com/position/) - the user says what point of the element should be positioned to what point of the target. Is that realistic in the context of the `Position` component?  .

**Comment by jquense** [comment]
I think its reasonable for this component, however the major use case for it has been bootstrap tooltips,  which is mostly covered by the more simplistic placements. 

Which is to say that I am not sure anyone on the team haa the time or the use-case for adding more placements, but we'd happily accept a PR ;)

**Comment by bluetidepro** [comment]
@jquense @vladimir-rovensky Did you ever figure out a good way to handle this? Also looking to use positioning a bit more advance like `top left`, `bottom right`, etc. It's very useful to get the carrot in the right position for tooltips.

**Comment by vladimir-rovensky** [comment]
Not really, I ended up using [jquery-ui position](https://jqueryui.com/position/), it was the quickest solution I could think of, plus it handles collisions. Would be nice to have a pure react solution for this though.

**Comment by bluetidepro** [comment]
@vladimir-rovensky Do you have an example of how you did that and use jquery-ui positioning to do it?

**Comment by vladimir-rovensky** [comment]
I made a simple wrapper component kinda like this:

```
React.createClass({
    render(){
        return <div ref='child' style={{visibility: 'hidden', position: 'absolute'}}>{this.props.children}</div>;
    },

    componentDidMount(){
        $(this.refs.child).position({
            my: this.props.my,
            at: this.props.at,
            of: this.props.of(),
            collision: 'flip flip'
        }).css({visibility: 'visible'});
    }
});
```

Then use it like:
```
return    <Position my='left top' at='left bottom' of={() => this.refs.head}>
                 ...
          </Position>
```

**Comment by bluetidepro** [comment]
@vladimir-rovensky hmmmm, I don't think I follow the full context of what/how you did that. Do you have a larger snippet? :/ ha Sorry for the hassle!

**Comment by bluetidepro** [comment]
@vladimir-rovensky Does that also support a way to do like an "auto" position?

**Comment by vladimir-rovensky** [comment]
There's not much more to it, that's literally the whole thing. It uses jquery.ui position to do a one time (when it mounts) positioning of its children to a given target. To elaborate on the usage:
```
return    <div>
              <div ref='target'>I am the target</div>
              <Position my='left top' at='left bottom' of={() => this.refs.target}>
                  <div>I will be positioned below the target</div>
             </Position>
          </div>
```
Not sure what you mean by auto position, if you mean to automatically reposition the children to keep their relative position to the target even when it moves/resizes, then no, this is just a one time positioning. If your target moves around, you'd have to keep updating the position in `componentDidUpdate` and make it so that Position is re-rendered whenever the target moves.

**Comment by bluetidepro** [comment]
@vladimir-rovensky Thank you for your help. I did end up getting it to work well! I think my only problem left is this method doesn't seem to play nice with the `Transition` comp. Did you use that by any chance in your flow with this method?

**Comment by vladimir-rovensky** [comment]
Unfortunately I didn't, I'm not familiar with that one :-(

**Comment by jacques-interana** [comment]
Is there a way I can vote for this?  My use case is that I'm trying to make a custom dropdown component using react-overlays, and I want the dropdown menu to be left-aligned with the dropdown button.  It would be nice if Position knew how to do this out of the box (surely react-bootstrap's built-in dropdown component could also benefit from this?), but I would even settle for some kind of clean way to substitute my own position calculation logic for the simplistic logic hard-coded into Position.  I mean if Position even just exposed the bounding rectangles of the dropdown button and dropdown menu to the child dropdown menu component as a prop, instead of doing the simplistic calculation itself and giving me only the results of that calculation in the style prop, I would be overjoyed.  Maybe I should send a PR or something?

**Comment by nitin-pai** [comment]
I was looking for the same feature. I am using react overlay to create a context menu dialog on a grid row and needed a "bottom" + "right" placement. But since its not supported as of now, is there any other way to build content menus with such placements.

**Comment by devongovett** [comment]
Made a pull to address this: #175. Allows alignments along the cross-axis other than center, e.g. `"bottom right"`.

**Comment by taion** [comment]
I believe this is now irrelevant.
