### ISSUE TITLE
Updating the position on window resize.

### ISSUE THREAD

**Issue by SamvelRaja** [react-bootstrap/react-overlays#54]
It will be better to adjust the position based on the based on window resize event.

**Comment by jquense** [comment]
adjust the position of what?

**Comment by SamvelRaja** [comment]
Right now i am using the overlays to position my tooltips, which are not adjusting by themselves when the window size gets resized.

**Comment by saltycrane** [comment]
@jquense here is an animated gif showing what I think @SamvelRaja is talking about:
![egh04t4uii](https://cloud.githubusercontent.com/assets/25131/12342060/7e90c4b8-badb-11e5-930b-5b9bce153342.gif)

@SamvelRaja probably noticed this since he created https://github.com/react-bootstrap/react-overlays/issues/55, but https://github.com/react-bootstrap/react-overlays/pull/42 is useful for solving this issue. It allows me to do:

```javascript
  componentDidMount() {
    util.throttleEvent('resize', 'throttledResize');
    window.addEventListener('throttledResize', this._onResize);
  }

  _onResize = () => {
    this.forceUpdate();
  };

  render() {
    return (
      <span>
        <OverlayTrigger shouldUpdatePosition={true} trigger="click" rootClose placement="bottom" overlay={ <MyPopover /> } >
          <a tabIndex="0" role="button" className="popover-help-trigger"></a>
        </OverlayTrigger>
      </span>
    );
  }
```

Without https://github.com/react-bootstrap/react-overlays/pull/42 I need to use a hack to make it work:

```javascript
  state = {
    placement: "bottom"
  };

  componentDidMount() {
    // util.throttleEvent('resize', 'throttledResize');
    // window.addEventListener('throttledResize', this._onResize);
    window.addEventListener('resize', this._onResize);
  }

  _onResize = () => {
    // HACK: to make open popover move when resizing the window
    this.setState({placement: 'right'});
    this.setState({placement: 'bottom'});
  };

  render() {
    return (
      <span>
        <OverlayTrigger trigger="click" rootClose placement={this.state.placement} overlay={ <MyPopover /> } >
          <a tabIndex="0" role="button" className="popover-help-trigger"></a>
        </OverlayTrigger>
      </span>
    );
  }
```

**Comment by SamvelRaja** [comment]
Exactly @saltycrane  and toggling the state creating a flick which is not good a approach as well :disappointed:

**Comment by jquense** [comment]
Hey folks, thanks for the responses

I am inclined to say that the right way to deal with this is to make use of the `container` prop to "attach" the tooltip to an element that moves with the flow of the document. (notice this example: http://react-bootstrap.github.io/components.html#popovers-in-container)

The downside to doing resize is the performance cost, which matters with lots of tooltips on screen

ref: https://github.com/twbs/bootstrap/issues/9517

**Comment by taion** [comment]
You'd need both that and listening to the resize event, right?

**Comment by jquense** [comment]
I suppose it depends on the situation, but yeah, maybe this is something we turn on with shouldPositionUpdate?

**Comment by taion** [comment]
I feel like attaching a window resize listener automatically is a little janky though.

Maybe offer some utility component for this functionality?

**Comment by saltycrane** [comment]
Thanks for the responses. I'm still struggling with getting the positioning right, but I think using the `container` prop solves my window resizing problem. I did not know about that prop. Thanks.

**Comment by SamvelRaja** [comment]
Thanks all.. It really helps a lot. Go ahead and close the issue if you needs to.
