### ISSUE TITLE
docs: broken sidebar link & not responsive

### ISSUE THREAD

**Issue by malsf21** [react-bootstrap/react-overlays#540]
Hey! I was looking at the documentation page at [https://react-bootstrap.github.io/react-overlays/](https://react-bootstrap.github.io/react-overlays/) and noticed a few things:

* the "Positions" link on the sidebar doesn't point to anything
* "Dropdown" and "Overlay" should be swapped to match the order on the page
* after < 990px the sidebar collapses into the page content, rendering it unusable

Is a fix already in the works? If not, I can take a crack at it with a PR.

**Comment by mxschmitt** [comment]
I don't think so. Would be awesome if you could create a PR to fix these issues.

**Comment by malsf21** [comment]
Sounds good, I'll work on it. Shouldn't be too hard!

**Comment by malsf21** [comment]
Actually, @mxschmitt I'm a bit confused. The development version (cloned from `master`) is not the same as what's live on [https://react-bootstrap.github.io/react-overlays/](https://react-bootstrap.github.io/react-overlays/); and the problem is fixed on `master`. I'll close the issue, but I think the deployment needs to be updated.
