### ISSUE TITLE
Affix component's affixStyle should override the child's style

### ISSUE THREAD

**Issue by kenny-f** [react-bootstrap/react-overlays#56]
I believe
```
return React.cloneElement(child, {
      className: classNames(affixClassName, className),
      style: {...positionStyle, ...affixStyle, ...style}
    });
```
should be 
```
return React.cloneElement(child, {
      className: classNames(affixClassName, className),
      style: {...positionStyle, ...style, ...affixStyle}
    });
```

For example, if I have a navbar with a background color of white initially and I want the affixed color to change when I scroll down the page it doesn't happen because currently the default style overrides the affix style

**Comment by jquense** [comment]
I can see the use case here, but I am tempted to say that switching the order would limit use cases more than allow them, since you no longer can adjust positions manually?

@taion any opinion here?

**Comment by taion** [comment]
IMO user-specified styles should be the final word.

Otherwise with `topStyle`, `affixStyle`, and `bottomStyle`, you can do whatever else you need.
