### ISSUE TITLE
ReactDom FindDOMNode undefined

### ISSUE THREAD

**Issue by amitthakkar22288** [react-bootstrap/react-overlays#59]
i get this error when i try to use overlays

_reactdom2.default.findDOMNode is undefined.

Can i use the latest version 0.6.0 on React 0.13.3? 
even after going back to older version 0.3.0, i get the same error

`<Overlay
          show={this.state.show}
          onHide={() => this.setState({ show: false })}
          placement={this.state.placement}
          container={this}
          target={ props => findDOMNode(this.refs.target)}
        >
          <ToolTip>
            I'm placed to the: <strong>{this.state.placement}</strong>
          </ToolTip>
        </Overlay>`

**Comment by taion** [comment]
`package.json` marks the compatible React versions. You possibly have to go back farther than that.
