### ISSUE TITLE
Position for Tooltips offset

### ISSUE THREAD

**Issue by grydstedt** [react-bootstrap/react-overlays#61]
Trying to debug this and have hit a dead end. It seems like all my tooltips from `react-bootstrap` is offset by 5-10 pixels. 

My only ideas is that flexbox might be introducing unreliable offset from the parent containers.

Any ideas how to debug this further?
![screen shot 2016-02-03 at 6 02 58 pm](https://cloud.githubusercontent.com/assets/782394/12803864/bdaa20c8-caa2-11e5-96d5-1d58a12cf6ba.png)

**Comment by taion** [comment]
Can't do anything here without a repro. If you're using a container, though, check that the container is a positioned element.
