### ISSUE TITLE
Alternatively Position with 'right' and 'bottom' 

### ISSUE THREAD

**Issue by pcwinters** [react-bootstrap/react-overlays#67]
The `<Position>` component applies 'left' and 'top' positioning styles. It would be useful to support positioning with 'right' or 'bottom'.

**Comment by jquense** [comment]
you can place things to the right or bottom it's just  expressed as top and left coordinates. not sure what the advantage of using different properties here, care to elaborate?

**Comment by pcwinters** [comment]
Right and Bottom are placement options. I'm referring to an option where an overlays positioning is expressed in terms of right and bottom coordinates. I'm willing to submit a pull request if the feature gets a thumbs up. Calculating offsets from the right or bottom should be pretty similar to doing it from left and top. I believe it would be expressed as a Position prop type, something like `xRelativeTo="right"'` that defaults to "left".

For example, I have a a trigger and overlay that are basically right aligned against the window. Based on a condition, I want the overlay to expand in width w/ a css transition on 'min-width'. Since the positioning is based on left-coordinates, the overlay then overflows the window and causes a scroll-bar. If the positioning was expressed w/ 'right', then the actual positioning of the overlay would never change and the expanding behavior wouldn't overflow. I have to jump through hoops right now to forceUpdate <Position> properties now based on width changes internal to the overlay.

**Comment by jquense** [comment]
I'm open to a PR, provided it doesn't over complicate the default case. thanks for that!

**Comment by taion** [comment]
Closing this for age. We'd consider a PR here, but we don't actively consider this a missing feature.
