### ISSUE TITLE
rootClose is triggered on right click in firefox 

### ISSUE THREAD

**Issue by adamziel** [react-bootstrap/react-overlays#68]
RootCloseWrapper.js tags `click` events in `getSuppressRootClose`. There is an inconsistency in firefox between events received by handlers registered via `onClick` react attribute and `document.addEventListener`:

```js
  bindRootCloseHandlers() {
    const doc = ownerDocument(this);

    this._onDocumentClickListener =
      addEventListener(doc, 'click', this.handleDocumentClick);
```

```js
    return (
      <div onClick={this._suppressRootCloseHandler}>
```

the `onClick` handler will not receive right clicks in firefox:
https://github.com/facebook/react/blob/c5f7c8dae179b621de5fc9fbc4113a0e3536bbfd/src/renderers/dom/client/eventPlugins/SimpleEventPlugin.js#L550

so `_suppressRootCloseHandler` will not be called and therefore every right-click will result in closing the overlay.

**Comment by taion** [comment]
If `onClick` isn't getting triggered, then what's the problem?

**Comment by adamziel** [comment]
great questio, this is the problem:
https://github.com/facebook/react/blob/c5f7c8dae179b621de5fc9fbc4113a0e3536bbfd/src/renderers/dom/client/eventPlugins/SimpleEventPlugin.js#L550

**Comment by adamziel** [comment]
actually my original description was inaccurate, I just updated it

**Comment by taion** [comment]
I see. I think the best fix here is to update `handleDocumentClick` to only deal with unmodified left mouse button clicks.

Thoughts? cc @jquense

**Comment by jquense** [comment]
sounds like a fair constraint to me

**Comment by taion** [comment]
@adamziel Want to put together a PR? It's just this logic: https://github.com/reactjs/react-router/blob/0e05964f381e151eb52b1321ea8d73d8c1f49f4e/modules/Link.js#L79-L80.

**Comment by adamziel** [comment]
@taion Sure! I'll post one later
