### ISSUE TITLE
v0.4.0 is missing lib/ and built code

### ISSUE THREAD

**Issue by cesarandreu** [react-bootstrap/react-overlays#7]
Probably a small mistake, but you pushed v0.4.0 and when you install it it doesn't include the built lib.

This is what you get when you install it:

![react-overlays installed](https://cloud.githubusercontent.com/assets/656870/9075045/0e2264c0-3ac5-11e5-940a-3838f708d7a0.png)

**Comment by jquense** [comment]
hehe sorry about that I was testing out the release scripts and thought that might be the case but got called away will fix!

**Comment by jquense** [comment]
ok 4.1 is out and should be good

**Comment by cesarandreu** [comment]
Thanks :D
