### ISSUE TITLE
AutoAffix not overlay over input and other elements

### ISSUE THREAD

**Issue by huvber** [react-bootstrap/react-overlays#71]
I'm using your `react-bootstrap` library with this one and I noticed when AutoAffix is activated some of the elements doesn't go down the AutoAffix element but instead stay over. 
![image](https://cloud.githubusercontent.com/assets/5032333/14019565/b5f06c68-f1d3-11e5-81b5-5b5418ce34e7.png)

As you can see this especially happened with `Glyphicon`, `Input`, and `Pagination`elements

**Comment by taion** [comment]
We don't control any of the CSS beyond the positioning – to the extent you need to set up a z-index or whatever here, this is on you.
