### ISSUE TITLE
itemSelector of Dropdown component is not required

### ISSUE THREAD

**Issue by Viktor-the-great** [react-bootstrap/react-overlays#747]
## Describe the bug

My editor highlight Dropdown component to pass required itemSelector. itemSelector has default value

**Comment by taion** [comment]
This seems like a bug with your editor, then.

**Comment by Viktor-the-great** [comment]
> This seems like a bug with your editor, then.


I think it's normal that editor requires you to pass required props. If prop (itemSelector) has a default value, then why indicate it as required?

**Comment by taion** [comment]
They're not semantically identical. If you don't mark it "required", then explicit null and undefined values become allowed.
