### ISSUE TITLE
react-dom peer dependency

### ISSUE THREAD

**Issue by donpark** [react-bootstrap/react-overlays#75]
With React.js v15, following warning is emitted:

    npm ERR! peer dep missing: react-dom@^0.14.0, required by react-overlays@0.6.2

To fix this, `react-dom` entry in `peerDependencies`

    "react-dom": "^0.14.0"

should be changed to:

    "react-dom": ">=0.14.0"

**Comment by taion** [comment]
CI currently doesn't pass against React 15, so I need to make sure it works first.

**Comment by donpark** [comment]
OK. I tried using a patched version but got errors like:

    Cannot find module 'react-overlays/lib/Modal'

So I looked into `node_modules/react-overlay` and found that `lib` directory was missing. npm install via git repository URL has issues.

**Comment by taion** [comment]
Installs directly from source don't work, and they're not supposed to either.

**Comment by donpark** [comment]
Good to know. thx

**Comment by taion** [comment]
v0.6.3
