### ISSUE TITLE
Include RootCloseWrapper as part of public API

### ISSUE THREAD

**Issue by cesarandreu** [react-bootstrap/react-overlays#77]
`RootCloseWrapper` is small but definitely useful on its own. What are your thoughts about adding it as part of the public API?

**Comment by jquense** [comment]
I'm a fan :+1:

**Comment by taion** [comment]
Sounds good.

**Comment by taion** [comment]
@cesarandreu Did you want to put together a PR?

**Comment by leojh** [comment]
was anyone already working on this? if not, I'd be happy to try to do it this weekend.

**Comment by taion** [comment]
I'm not aware that anyone is working on this.

**Comment by andresgutgon** [comment]
I'm working on that ☝️

**Comment by wzup** [comment]
Was the feature implemented or not?

**Comment by taion** [comment]
No.

**Comment by wzup** [comment]
@taion 

There are at least three files that import `RootCloseWrapper`
https://github.com/react-bootstrap/react-bootstrap/blob/a1a98485f1147654f244a201a3fe638b9a8333ec/src/DropdownMenu.js
https://github.com/react-bootstrap/react-overlays/blob/54a1fc47e09985a74d26a07982d94689a63cf46d/test/RootCloseWrapperSpec.js
https://github.com/react-bootstrap/react-overlays/blob/a268df0b60f3ec2b5afe5bb3456509274ba6f72c/src/Overlay.js

And here is a file with exactly the same component [RootCloseWrapper](https://github.com/react-bootstrap/react-overlays/blob/54a1fc47e09985a74d26a07982d94689a63cf46d/src/RootCloseWrapper.js)

So is it implemented? 

What's exactly is this component for? I need functionality that closes customized dropdown by clicking screen anywhere outside the dropdown. Is this the component that represents this functionality?

**Comment by Morantron** [comment]
I read in #111 that docs are a blocker for this issue. What can we do to have this merged? Would commenting the code and adding some examples in `examples` folder be enough? Or would you need some examples in `gh-pages` branch as well?

**Comment by aatrostle** [comment]
✋ I would love to help add docs to get this shipped, can I get a pointer to where to do that?

**Comment by jquense** [comment]
the prop descriptions are generated from comments in the components and the docs are in the doc folder :thumbsup:

**Comment by aatrostle** [comment]
_:gentle-nudge:_ #77 has been reviewed once and AFAIK should be good to go, let me know if theres anything else I need to address for it to ship.
