### ISSUE TITLE
React 15 support

### ISSUE THREAD

**Issue by brucek** [react-bootstrap/react-overlays#78]

**Comment by taion** [comment]
This lib supports React 15 just fine.

**Comment by jharris4** [comment]
It does indeed, but we still get a warning:

``
react-overlays@0.6.2 requires a peer of react-dom@^0.14.0 but none was installed.
``

Not a huge deal, but would be nice to add the || ^15.0.0 to the package.json dependencies...

**Comment by taion** [comment]
Reinstall – the new react-overlays (v0.6.3) fixes this.

**Comment by jharris4** [comment]
Oh I see, I'm still on react-bootstrap 0.28.5 and don't have a direct dependency on react-overlays. Reinstalling react-bootstrap did fix the warning. Thanks!

**Comment by taion** [comment]
Yeah, sorry about that – it didn't seem quite worthwhile to cut a new release just for a transitive dep bump on a patch version.
