### ISSUE TITLE
Explanation of breaking changes in 3.0?

### ISSUE THREAD

**Issue by dmsnell** [react-bootstrap/react-overlays#783]
> BREAKING CHANGES
>
> popper upgrade to v2, slightly different modifiers format now

The release notes for 3.0 indicate that something big changed but I didn't see _what_ changed and _how_. Is there a link to explain what modifiers were impacted? Is there a way to know what we'll need to update in our applications based on this breakage?

**Comment by jquense** [comment]
Check out the changelog. The only change is the upgrade to popper v2 which has a different config format, only matter is you use popperConfig directly

**Comment by dmsnell** [comment]
Thanks @jquense - I was actually _quoting_ the changelog.

Is `popper` relevant to users of this library? I currently use `react-overlays` but I don't have anything for `popper` in my code. I'm asking for clarification since the changelog indicates that this is a breaking change - I'm nervous that by not knowing what I'm supposed to update my app will break in an unexpected way.

**Comment by jquense** [comment]
It was a breaking change for a particular prop on overlay and drop-down. Popper is used internally for positioning and is mostly abstracted away, but we do expose the underlying API for users who want to customize. If you are unfamiliar with popper it's probably safe to assume you aren't using anything that has changed.

**Comment by dmsnell** [comment]
>  If you are unfamiliar with popper it's probably safe to assume you aren't using anything that has changed.

Thanks! This is what I was hoping to hear. (Wouldn't be a bad addition to the changelog)

**Comment by amitava82** [comment]
This actually. broke my tooltip. I have following props OverlayTrigger
```
  popperConfig={{
        modifiers: {
          preventOverflow: {
            enabled: true,
          }
        }
      }}
```
For an element placed at the top of the page, the tooltip position do not shift from top to bottom when it is going outside viewport.
