### ISSUE TITLE
fix: documentation deployment

### ISSUE THREAD

**Issue by mxschmitt** [react-bootstrap/react-overlays#786]
## Describe the bug

Currently the documentation deployment on master is always erroring.

cc @bpas247 would be awesome if you could take a look

**Comment by bpas247** [comment]
@mxschmitt so #430 was supposed to fix that, but it's still [blocked](https://github.com/react-bootstrap/react-overlays/pull/430#discussion_r319869558) due to a GitHub secret that needs to be added to this repository.

**Comment by mxschmitt** [comment]
> @mxschmitt so #430 was supposed to fix that, but it's still [blocked](https://github.com/react-bootstrap/react-overlays/pull/430#discussion_r319869558) due to a GitHub secret that needs to be added to this repository.

seems like only @jquense and @taion can do that right? Otherwise we could also just redirect from the GitHub Pages hosting to Netlify which does not rely on that. Would also solve the issue that we have multiple documentations running.

**Comment by taion** [comment]
oh oops, checking

**Comment by mxschmitt** [comment]
Seems fixed!
