### ISSUE TITLE
examples in the docs do not work

### ISSUE THREAD

**Issue by DanielRuf** [react-bootstrap/react-overlays#793]
## Describe the bug

Nothing happens when I click the buttons in the examples.

## To Reproduce

1. Go to the docs and try any modal button.

## Expected behavior

A modal should open.

## Environment (please complete the following information)

- Operating System: [e.g. macOS]
- Browser, Version Firefox
- react-overlays Version [e.g. 2.0.0]

**Comment by mxschmitt** [comment]
Try them: https://react-overlays.netlify.com/dropdown

cc @jquense can you redeploy the docs to the GitHub Pages site? Seems like already fixed on master.
