### ISSUE TITLE
AutoAffix - layout jumps up once affixed

### ISSUE THREAD

**Issue by jwbay** [react-bootstrap/react-overlays#80]
Example code:
```jsx
class AffixExample extends React.Component {
  render() {
    return (
      <div className='affix-example'>
        <AutoAffix viewportOffsetTop={30} container={this}>
          <div className='panel panel-default'>
            <div className='panel-body'>
              I aaaam an affixed element
            </div>
          </div>
        </AutoAffix>
        <p>Other content asdf</p>
      </div>
    );
  }
}

React.render(<AffixExample/>, mountNode);
```

Initial layout:
![one](https://cloud.githubusercontent.com/assets/1320447/14763277/09392dc2-095f-11e6-9593-652023290b8b.png)

Scrolled one pixel down to trigger the affix (opacity added via devtools):
![two](https://cloud.githubusercontent.com/assets/1320447/14763282/17414e04-095f-11e6-8d7e-4b0f5e84b17a.png)

Once `position: fixed` is applied, I believe there needs to be some kind of placeholder inserted with an equal height in order to keep sibling content from jumping up.

As far as a solution, this worked for me, but it's kind of a mess. Is there a better approach or would you take a PR with something like this?

```jsx
import * as React from "react";
import AutoAffix from "react-overlays/lib/AutoAffix";

export default class AffixWrapper extends React.Component {
	componentWillMount() {
		this.setState({ affixed: false });
	}

	render() {
		return (
			<div>
				<AutoAffix { ...this.props }
					onAffix={ () => this.setState({ affixed: true }) }
					onAffixTop={ () => this.setState({ affixed: false }) } >

					<div ref={ c => this.content = c }>
						{ this.props.children }
					</div>

				</AutoAffix>

				{ this.state.affixed &&
					<div style={ { width: "100%", height: this.contentHeight } } />
				}
			</div>
		);
	}

	componentDidMount() {
		this.updateHeight();
	}

	componentDidUpdate() {
		this.updateHeight();
	}

	updateHeight() {
		this.contentHeight = Math.max(
			this.content.scrollHeight,
			this.content.offsetHeight,
			this.content.clientHeight
		);
	}
}
```

**Comment by jquense** [comment]
the best/simplest way to handle this is a css selector 

```js
.affixed + * {
  margin-top: 30px; //or whatever the height of your content is.
}
```

anything else is gonna be too error prone to do in a way that is nicely generalizable.

**Comment by jwbay** [comment]
Got it. I've got a few too many places to manage hardcoded heights, so I'll have to keep the wrapper approach for now. Thanks for taking a look!

**Comment by itajaja** [comment]
hey @jquense seems like I am not able to apply your method easily. Here is my snippet:

```js
<AutoAffix viewportOffsetTop={105} affixClassName="affixed">
  <p>AFFIXED HEADER</p>
</AutoAffix>
<div>other content</div>
```

The resulting DOM though is not as I'd expect:

![image](https://cloud.githubusercontent.com/assets/697647/15996126/6191859a-30f2-11e6-9fea-9a64da8e8eca.png)

The "affixed" class is wrapped inside a div, which basically makes the selector not apply to the "other content" div. I could use the listeners to set the state and dynamically apply classes, but it's not as easy as your selector solution. Am I missing somehting?

**Comment by itajaja** [comment]
After a brief inspection, it works with `Affix` but not with AutoAffix (reason being in this [wrapping](https://github.com/react-bootstrap/react-overlays/blob/master/src/AutoAffix.js#L132-L145)) not sure what's the best way to handle with this problem in this case then

**Comment by jquense** [comment]
@itajaja I'm not actually sure myself there...the wrapper makes everything more difficult. let me look at how I've handled this elsewhere.

**Comment by taion** [comment]
Might be better to use a `position: sticky` polyfill? I don't think the TWBS Affix does anything particularly clever here anyway.

Otherwise hardcode the height.

**Comment by karlshea** [comment]
It would be great if there were an onUnAffix callback, that would help to solve this issue.

**Comment by jquense** [comment]
@karlshea those are `onAffixTop` or `onAffixBottom`

**Comment by madhums** [comment]
The extra div's makes it really complicated to use AutoAffix component. 

1. Can't use `.affixed + *` as there is no element after the affixed element.
2. `onUnAffix` seems like a very good idea but neither `onAffixTop` or `onAffixBottom` are called while un-affixing. 

It adds a lot of value to fix this. Would it be of interest if I send a PR?

**Comment by madhums** [comment]
Apologies! `onAffixTop` works!

**Comment by gioragutt** [comment]
@jquense He meant to have a hook for when you stop affixing.

Also, has anyone found any general-case fix for this scenario?

**Comment by robdmoore** [comment]
Hmm it seems the above code snippet /does/ seem to work with AutoAffix afterall. :)
