### ISSUE TITLE
handleDocumentKeyDown is not updated when onHide callback is (ESC keydown works incorrect)

### ISSUE THREAD

**Issue by Ronny25** [react-bootstrap/react-overlays#803]
## Describe the bug

When onHide callback is updated it's correctly triggered after clicking on backdrop.
However, the old callback reference is triggered after pressing ESC key.
Seems, **handleShow** is not updating event callback.

## To Reproduce

1. Place react-overlays Modal component into FunctionComponent.
2. Pass **onHide** callback into it, where you are checking for anything like **isLoading**.
3. When ESC key is pressed callback is fired but **isLoading** stays in previous condition even when it's actually has changed.

## Reproducible Example

Minimal example https://codesandbox.io/s/esc-event-bug-e58il

## Expected behavior

Event callback needs to be updated as well as **onHide** is updated.

## Environment

- Operating System: macOS
- Browser, Version Chrome 81
- react-overlays Version 3.1.3

**Comment by taion** [comment]
ah, interesting; it's a bug around keeping the listener up-to-date
