### ISSUE TITLE
Documentation Page Doesn't Exist

### ISSUE THREAD

**Issue by arielspalter** [react-bootstrap/react-overlays#805]
The documentation link is broken. 

Thanks!

**Comment by mxschmitt** [comment]
Which one? https://react-bootstrap.github.io/react-overlays/ seems to work.

**Comment by arielspalter** [comment]
I was using the one on the main page: https://react-bootstrap.github.io/react-overlays/modal/
This one works perfectly fine! Thank you for the speedy response!

**Comment by mxschmitt** [comment]
Thanks for reporting, will be fixed soon. 👍
