### ISSUE TITLE
Modal: Use onEscapeKeyDown event preventDefault() to cancel onHide in handleDocumentKeyDown?

### ISSUE THREAD

**Issue by kyletsang** [react-bootstrap/react-overlays#815]
## Is your feature request related to a problem? Please describe

Would it be possible to use the keyboard event `defaultPrevented` to skip all subsequent calls inside the modal's `handleDocumentKeyDown`?

Background/motiviation is related to a discussion I had with @taion in a PR in react-bootstrap: https://github.com/react-bootstrap/react-bootstrap/pull/5165

## Describe the solution you'd like

If event.defaultPrevented is `true`, prevent `onHide()` from being triggered here:
https://github.com/react-bootstrap/react-overlays/blob/master/src/Modal.tsx#L281

**Comment by taion** [comment]
hi, do you want to just send in a quick PR here?
