### ISSUE TITLE
onHide on Overlay used in examples but having no functionality

### ISSUE THREAD

**Issue by jardakotesovec** [react-bootstrap/react-overlays#83]
If I understand correctly passing `onHide` function to `Overlay` is pointless, because `Overlay` nor `children` can takes advantage of it unless `rootClose` is used along with it.

Which is confusing since its used in [examples](http://react-bootstrap.github.io/react-overlays/examples/#overlay). Have you considered passing `onHide` to children to it can be called from there?

**Comment by taion** [comment]
There's not really a need to do that explicitly – you can do so yourself. We do much the same for modals.
