### ISSUE TITLE
useUncontrollableProp not exported by uncontrollable

### ISSUE THREAD

**Issue by tastyjingle** [react-bootstrap/react-overlays#831]
Installing the package and running 'npm start' or 'build' reports 'useUncontrollableProp not exported by uncrontrollable'

Strangely, it ran fine after the initial installation, however, the above error occurs if you restart your service.

The fix is relatively simple:
/react-overlays/esm/Dropdown.js  needs to be modified at lines 5 and 97.

line 5:
`import { useUncontrolled } from 'uncontrollable';`
line 97:
`var _useUncontrolledProp = useUncontrolled(rawShow, defaultShow, rawOnToggle),` 

At any rate, that was the approach I used to keep the change footprint as small as possible.

Cheers!

**Comment by taion** [comment]
This looks like an issue in your build pipeline that's somehow pulling in the wrong version of `uncontrollable`. It's likely that you're somehow deduplicating `uncontrollable` to an older version that doesn't have this API. This library's specified dependency range for `uncontrollable` points to the correct version with the correct API.

**Comment by tastyjingle** [comment]
strange, just did 'npm install react-overlays'. Might be some goofiness there. I'll take a look to see what might have gone wrong.

**Comment by marmax** [comment]
@taion JFYI `useUncontrolledProp` was (according to [the release notes](https://github.com/jquense/uncontrollable/blob/b732a7bcc3dd18ad7cb821a2e90b0f3216b01528/CHANGELOG.md) ) added in `7.1.0`, whereas react-overlay still refers to ` "uncontrollable": "^7.0.0",` ;-)
