### ISSUE TITLE
Outer Overlay(Popper) is getting closed on updating inner overlay(popper)  [RootClose: true]

### ISSUE THREAD

**Issue by ramareddy12345** [react-bootstrap/react-overlays#835]
We are opening inner overlay on button click inside outer overlay. both the overlays has Rootclose: true and both are appended to dom as siblings through portal.(container is body tag for both the overlays)

**Currentbehaviour**: useRootcloseWrapper hook doesn't have mechanism to check relate inner & outer overlay relation and considering it as different overlay and triggering onHide on outer overlay resulting in outer overlay getting closed.

Expected Behaviour:  usePopper should maintain stack of overlay hierarchy (After creating popper instance) and consider overlays relation in useRootcloseWrapper . Functionality should be similar to https://runfaj.github.io/react-nested-popper/#/nested

**Comment by taion** [comment]
dupe #836
