### ISSUE TITLE
Transition and Overlay

### ISSUE THREAD

**Issue by khankuan** [react-bootstrap/react-overlays#85]
Hi,

I'm trying to animate the Popover that vary according to placement. However, `transition` seems to be fixed to one transition class and i would need to create 1 Transition for each placement. Is there a better way to do it?

Thanks!

**Comment by taion** [comment]
You can read the position in the transition component and predicate based on that.

**Comment by khankuan** [comment]
Do you mean `props.children.props.placement`?

**Comment by taion** [comment]
Oh, I didn't realize we didn't spread everything into the `Transition`. I think in that case, your best bet given the current API is to make a separate transition class per placement.

**Comment by jquense** [comment]
I'm surpriseing myswlf here with this thought but... this seems like a good use case for a HoC
