### ISSUE TITLE
autoFocus is not working 1.0.0-beta.3 in Modal component

### ISSUE THREAD

**Issue by hardikmodi1** [react-bootstrap/react-overlays#862]
I am using the Modal component in 1.0.0-beta.2, but due to [this](https://github.com/react-bootstrap/react-overlays/pull/858) issue upgraded it to 1.0.0-beta.3 and it breaks the behaviour of autoFocus. Focus is not shifting to the modal when it opens up.

**Comment by jquense** [comment]
`1.0.0-beta.3` of react-bootstrap or react-overlays? In either case those are old versions, you should upgrade to the most recent
