### ISSUE TITLE
Feature request: automatic overlay placement

### ISSUE THREAD

**Issue by getaaron** [react-bootstrap/react-overlays#864]
## Is your feature request related to a problem? Please describe

I'm always frustrated when I have to specify the `placement` for an `Overlay`. With responsive design, it's often really difficult to pick a direction.

## Describe the solution you'd like

I’d like to request a 5th option in `placements`, `auto`, which would just pick an arbitrary placement far away from the edge of the user's browser window.

## Describe alternatives you've considered

I also considered an API like `permittedPlacements` where you could specify an array like `['up', 'down', 'left']` and it would automatically pick from those. (Similar to [iOS's `UIPopoverPresentationController`](https://developer.apple.com/documentation/uikit/uipopoverpresentationcontroller)).

## Additional context

n/a

**Comment by jquense** [comment]
you can do this already. `auto` is a valid placement
