### ISSUE TITLE
How to get more control over backdrop (I want to put an x mark on it)

### ISSUE THREAD

**Issue by reywright** [react-bootstrap/react-overlays#87]
Hey,

So I want to create a modal that has an x mark in the corner, and I'm having trouble.

![screen shot 2016-05-09 at 4 48 29 pm](https://cloud.githubusercontent.com/assets/708820/15127725/f0c8488c-1605-11e6-993c-ff443ee7828c.png)

So I have a reusable component encapsulating the react-overlay instance, and the same way that I'm passing a function to execute on hide, I'd like to be able to pass a function to the component encapsulating react-overlay that I can just execute.

    var RespModal = React.createClass({
        <Modal
            show={open}
            onHide={onClose}
            className={overlayClasses}
            containerPadding={0}
            containerClassName={containerClass}
            backdrop={false}>
            <div className={modalClasses}>
                <div className="modal-close" onClick={this.props.another}>X</div>
                {this.props.children}
                {loader}
            </div>
        </Modal>
    });

    <RespModal
        show={open}
        onHide={onClose}
        another={onClose}>
        content here
    </RespModal>

I don't know how much I need to flesh this out, but basically I needed more control over the backdrop so I put my own backdrop inside the modal, and that's been working fairly well. I either need a way to get more control over the backdrop, or I need to figure out how to give the encapsulating component itself the ability to take the close function and execute it. Any ideas? If I need to flesh out any ideas let me know.

**Comment by taion** [comment]
I wonder if it would make sense for `<Modal>` to accept a `renderBackdrop` hook.

**Comment by Aweary** [comment]
Maybe the `backdrop` prop (or another prop, to avoid a polymorphic props API) should accept a React component that would be returned instead of the default backdrop element.

**Comment by taion** [comment]
I think these days `renderFoo` callbacks are preferable, just because of the additional flexibility.

**Comment by karlguillotte** [comment]
Reading this issue and the first thing that come to my mind was *CSS before or after pseudo-classes*. Perhaps they could do the job!

**Comment by taion** [comment]
@jquense Added a `renderBackdrop`

**Comment by jquense** [comment]
ah here is that issue, thanks @taion

**Comment by reywright** [comment]
awesome, thanks guys.

**Comment by reywright** [comment]
@jquense I don't think renderBackdrop works... I'm trying to find the code where you guys added this? Is it merged in yet?

**Comment by reywright** [comment]
@taion renderBackdrop was never added

**Comment by reywright** [comment]
```
let backdropElement = (<div className="hey"></div>);

return (
            <Modal
                show={open}
                style={modalStyle}
                renderBackdrop={backdropElement}
            >)
```

Do you spot anything weird here?

**Comment by jquense** [comment]
yes renderBackdrop should be a function. Also there _is_ a bug where it's not being used when there is no Transition, see #160

**Comment by reywright** [comment]
@jquense awesome. adding that transition gets it working. thanks.
