### ISSUE TITLE
@popperjs/core 2.5.0 post-install fails

### ISSUE THREAD

**Issue by zapbulon** [react-bootstrap/react-overlays#871]
## Describe the bug

@popperjs/core v. 2.5.0 was just realased and its post-install fails. I tracked its usage in the lock file to 
`"react-overlays": {
      "version": "3.2.0",
      "requires": {
         "@popperjs/core": "^2.0.0",`

## To Reproduce

1. Do `npm install` with react-overlays 3.2.0

## Expected behavior

NPM install success

## Environment (please complete the following information)

- Operating System: [Linux Mint / Ubuntu]

## Additional context

Freezing @popperjs/core to 2.4.4 fixed it for me. I don't know whether it is a popperjs issue but it may be a good idea to freeze to previous version until they fix it.

**Comment by kyletsang** [comment]
This should be fixed with popper core 2.5.1.
