### ISSUE TITLE
Overlay && Transition

### ISSUE THREAD

**Issue by Nirazul** [react-bootstrap/react-overlays#88]
I've looked in every documentation I've found and waded through many blog articles but I couldn't find an example that shows a `Overlay` component in conjunction with a `Transition` component.

I'm building a simple ToolTip component on the basis of your [overlay example](http://react-bootstrap.github.io/react-overlays/examples/#overlay):

Overlay:
```
        return (
                <Overlay
                    show={this.state.showWarning}
                    onHide={() => this.setState({ showWarning: false })}
                    placement={'top'}
                    container={this.refs.compareWrap}
                    target={ (props) => ReactDOM.findDOMNode(this.refs.compareLink) }
                    transition={TransitionTooltip}>
                        <ToolTip>
                            <span>My tooltip.</span>
                        </ToolTip>
                </Overlay>
        );
```

Transition (includes my current workaround):
```
class TransitionTooltip extends React.Component {
    static propTypes = {};

    static defaultProps = {
        in: false,
        timeout: 250,
        unmountOnExit: false,
        transitionAppear: false
    };

    constructor(props) {
        super(props);
        this.state = {};
    }

    render() {
        const classlist = this.props.children.props.container.classList;

        return (
            // TODO: The entry and leave animations do not work with `enteredClassName`. This is a workaround:
            <Transition
                {...this.props}
                className="trs-tooltip"
                enteredClassName="trs-tooltip__entered"
                enteringClassName="trs-tooltip__entered"
                onEntering={ () => { classlist.add('tooltip-root__is-visible'); } }
                onExiting={ () => { classlist.remove('tooltip-root__is-visible'); } }>
                {this.props.children}
            </Transition>
        );
    }
}
```

I have already a working example with `Modal` and `Transition`, but I can't seem to make it work with an Overlay.

**Comment by jquense** [comment]
we use a Transition component in react-bootstrap: https://github.com/react-bootstrap/react-bootstrap/blob/master/src/Overlay.js

Not sure what exactly isn't working but css animation is a fickle mistress :/

**Comment by Nirazul** [comment]
As far as I can tell, the `Transition` component goes through the callbacks (`onEntering` etc) correctly, but doesn't apply any classes. The transition component does set them correctly, though.
I'd be willing to make a fiddle but I can't find a js file to import `react-overlays`. Do you know of any jsfiddle or something similar to test it?

**Comment by jquense** [comment]
you can try http://www.webpackbin.com/

**Comment by Nirazul** [comment]
I managed to solve the issue. The problem was that my custom `ToolTip` component didn't pass on the received className prop to its root element. That's why the classes never showed up and no animation was playing...
Thanks for helping me :)

**Comment by Nirazul** [comment]
Maybe this would be a fine use case to include in your docs.
