### ISSUE TITLE
@babel/runtime in dependencies

### ISSUE THREAD

**Issue by daveisfera** [react-bootstrap/react-overlays#881]
## Describe the bug
`@babel/runtime` is listed in `dependencies` but it should be listed in `devDependencies` or `peerDependencies`

## Expected behavior
`@babel/runtime` is pulled in by the user of `react-overlays`

**Comment by jquense** [comment]
that is correct, babel runtime is a dependency, it's supposed to be since it's required to use the package. A peer dep is not really appropriate either.

**Comment by daveisfera** [comment]
Why doesn't peer dependency make sense? Shouldn't the user of `react-overlays` be setting up/configuring `babel` and including the runtime as appropriate for that?

**Comment by jquense** [comment]
the runtime is stuff the the compiled code needs to function. regardless of whether you use babel or not react-overlays needs it, since a user is always consuming the compiled react-overlays code. It's functionally the same is any other dependency we use

**Comment by daveisfera** [comment]
I'm definitely not an expert in this arena and maybe there's something I'm missing, but the babel documentation seems to [imply that a direct dependency like this shouldn't be needed](https://babeljs.io/docs/en#compact)

**Comment by jquense** [comment]
it's all kind of obtuse i agree. This is definitely correct tho. https://babeljs.io/docs/en/babel-runtime#usage

**Comment by daveisfera** [comment]
👍
