### ISSUE TITLE
Dom-helper container width should consider scrollbar

### ISSUE THREAD

**Issue by khankuan** [react-bootstrap/react-overlays#89]
Hi, it seems like dom-helper is using `window.innerWidth` to get container width. This causes an incorrect offset computation in `Position` when the scrollbar is active. Are there any workarounds for it?

**Comment by jquense** [comment]
Hi there. What specifically do you consider wrong here? If you are positioning an overlay to the viewport you don't want to not include the scrollbar, since you are concerned with the viewport

**Comment by khankuan** [comment]
https://github.com/react-bootstrap/react-overlays/blob/master/src/utils/overlayPositionUtils.js#L11

I'm using it with a content that has 100% width. Unfortunately due to the condition above, im getting `left: 15px`.

**Comment by khankuan** [comment]
Actually, document.body.getBoundingClientRect().width gives a different value from window.innerWidth. Is there a reason that body's width calculated using window?
