### ISSUE TITLE
Enforce focus not working

### ISSUE THREAD

**Issue by viridia** [react-bootstrap/react-overlays#91]
I've traced through this in the debugger - when I have focus set to the last element in the modal and I press TAB, the 'enforceFocus' callback is not getting called, and so focus trapping is not happening.

The way I've handled this in past projects is to create invisible focusable elements at the beginning and the end of the modal, which when focused reset the focus to the last and first field respectively.

**Comment by jquense** [comment]
the focus is probably leaving the page, entirely, and being set the the browser chrome, this is normal/expected, when you focus fast the last focusable item on a page. If you keep hitting tab eventually the focus will return to the page, and be caught and transfered back to the modal
