### ISSUE TITLE
NPM Latest version is pointing to a bug fix branch

### ISSUE THREAD

**Issue by dozoisch** [react-bootstrap/react-overlays#913]
![image](https://user-images.githubusercontent.com/4422516/105560372-6d2fdd00-5cc8-11eb-842e-e62d7820e7c4.png)

Looks like 0.9.3 was published as latest instead of tagged version, which means "npm outdated" command returns 0.9.3 as the latest even for someone on 4.1.0

**Comment by jquense** [comment]
oops should be fixed now

**Comment by dozoisch** [comment]
thanks @jquense :)
