### ISSUE TITLE
onmousedown vs onclick?

### ISSUE THREAD

**Issue by glenjamin** [react-bootstrap/react-overlays#92]
Hello!

My main application is performing some actions on mousedown (like dragging).

The background overlay here only triggers onClick, this results in an effect where the overlays don't disappear when the user begins to interact with the application.

Would you be open to a PR which moves the background handlers onto `onMousedown` ?

**Comment by taion** [comment]
ref https://github.com/react-bootstrap/react-bootstrap/pull/1786

**Comment by glenjamin** [comment]
Seems related. Do you have any additional info about what problems that caused? Was the problem that the change should have been made over here, or something deeper?

**Comment by jquense** [comment]
@glenjamin check out https://github.com/twbs/bootstrap/issues/13816, I'm not sure what issues where caused. If you want to do some research and see if they are no longer issues, we can make the switch

**Comment by glenjamin** [comment]
Did a little bit more digging, the `Modal` doesn't really affect me at all - the overlay captures clicks and everything works as expected.

It's actually the `RootCloseWrapper` that I'm having trouble with, this binds to `click` on `document` to trigger the close - but allows the original event through as expected.

I did a quick trial of changing this to bind to `mousedown` and it worked as expected for me - but I'm unsure what else to check against.

**Comment by jquense** [comment]
done?
