### ISSUE TITLE
Repo "Wiki" is editable by anyone

### ISSUE THREAD

**Issue by aaronjedwards** [react-bootstrap/react-overlays#920]
I was exploring the repo and thought I would check the wiki for documentation, and turns out that it is openly editable to the public. I created a page, not believing it would work and it did! Now I can't delete it however.

It goes without saying, but you will probably want to [change the access permissions for the Wiki](https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis)

Thanks for the great utility!

**Comment by kyletsang** [comment]
Thanks for the heads up!
