### ISSUE TITLE
Where did AutoAffix go?

### ISSUE THREAD

**Issue by nicgordon** [react-bootstrap/react-overlays#953]
## Describe the bug

I am upgrading this package from an old version (0.9.3) and we are using the `AutoAffix` component. That does not seem to be exported from this package anymore but there is nothing in the changelog talking about its removal, nor can I seem to find the commit when it disappeared. 

Is there a suggested migration path for those using `AutoAffix`?

## To Reproduce

1. Install v0.9.3
2. Use the `AutoAffix` component via `import { AutoAffix } from 'react-overlays';`
3. Upgrade to v5.0.1

## Expected behavior

At least a note in the changelog about when it was removed and potentially a migration option.

**Comment by nicgordon** [comment]
Okay after some digging I found this PR https://github.com/react-bootstrap/react-overlays/pull/287 but there is nothing even on the description as to why it was removed or what consumers ought to do?

**Comment by jquense** [comment]
i don't really remember the context it was like 3 years ago i think? There isn't a real need for this component anymore `position: sticky` is very well supported now, and for old browsers better to use a sticky polyfill

**Comment by nicgordon** [comment]
Thanks for the reply @jquense. 

For any others that might stumble upon this here are some alternatives that I have found:
- https://github.com/yahoo/react-stickynode
- https://github.com/codecks-io/react-sticky-box
- https://github.com/gm0t/react-sticky-el

Or yes, write something custom using the `position: sticky` css property.
