### ISSUE TITLE
@popperjs/core@2.10.0 Causes NPM Errors

### ISSUE THREAD

**Issue by aarnold** [react-bootstrap/react-overlays#977]
## Describe the bug

Trying to build with `react-bootstrap` as a dependency produces NPM errors.

This seems to be related with the 2.10.0 version release of [popperjs](https://github.com/popperjs/popper-core/releases/tag/v2.10.0).

## Expected behavior

Should build without error

## Screenshots

```
18.26 ERROR in ./node_modules/react-overlays/esm/popper.js 1:0-55
18.26 Module not found: Error: Package path ./lib/modifiers/arrow is not exported from package /usr/src/app/node_modules/@popperjs/core (see exports field in /usr/src/app/node_modules/@popperjs/core/package.json)
18.26  @ ./node_modules/react-overlays/esm/Overlay.js 8:0-38 123:29-39
18.26  @ ./node_modules/react-bootstrap/esm/Overlay.js 5:0-49 43:42-53
18.26  @ ./node_modules/react-bootstrap/esm/OverlayTrigger.js 10:0-32 173:90-97
```

## Environment (please complete the following information)

- "react-bootstrap": "1.5.2",
- "bootstrap": "4.6.0",

## Additional context

Pinning @popperjs/core@2.9.3 seems to resolve the issue

**Comment by AhmedElywa** [comment]
I was going to open the same issue it happens when you using webpack 5

**Comment by bluematter** [comment]
> ## Additional context
> Pinning @popperjs/core@2.9.3 seems to resolve the issue

How do you pin that version? I updated my yarn.lock file which solved it but when deploying to vercel it breaks again.

**Comment by kyletsang** [comment]
There's a breaking change caused by https://github.com/popperjs/popper-core/pull/1342

Issue tracked upstream: https://github.com/popperjs/popper-core/issues/1361

**Comment by jerome-diver** [comment]
Thank you for the report, i have the same error with react-bootstrap-1.6.1, bootstrap-5.1.0 and webpack-5.28.0.
Do you find a way to fix the issue ?

**Comment by bluematter** [comment]
> Thank you for the report, i have the same error with react-bootstrap-1.6.1, bootstrap-5.1.0 and webpack-5.28.0.
> Do you find a way to fix the issue ?

Temporary hack is to update your lock files

**Comment by kyletsang** [comment]
There's a new version of popper that fixed this issue
