### ISSUE TITLE
Babel 6?

### ISSUE THREAD

**Issue by LeoAJ** [react-bootstrap/react-overlays#98]
Any plan to upgrade to babel 6 for this repo? I can help with that if that is a valid plan. Thanks!

**Comment by jquense** [comment]
go for it!

**Comment by taion** [comment]
Biggest issue might be the prop tables. See e.g. https://github.com/react-bootstrap/react-bootstrap/pull/1802.

**Comment by jquense** [comment]
react-metadata _Should_ be working with babel 6, i have react-formal updated to it
